package com.example.migration.dao.master.mapper;

import com.example.migration.dao.master.entity.CmsView;
import com.example.migration.dao.master.entity.CmsViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    long countByExample(CmsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    int deleteByExample(CmsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    int insert(CmsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    int insertSelective(CmsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    List<CmsView> selectByExampleWithRowbounds(CmsViewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    List<CmsView> selectByExample(CmsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CmsView record, @Param("example") CmsViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CmsView record, @Param("example") CmsViewExample example);
}