package com.example.migration.dao.master.mapper;

import com.example.migration.dao.master.entity.GenericLog;
import com.example.migration.dao.master.entity.GenericLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GenericLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    long countByExample(GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int deleteByExample(GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int insert(GenericLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int insertSelective(GenericLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    List<GenericLog> selectByExampleWithBLOBsWithRowbounds(GenericLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    List<GenericLog> selectByExampleWithBLOBs(GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    List<GenericLog> selectByExampleWithRowbounds(GenericLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    List<GenericLog> selectByExample(GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    GenericLog selectByPrimaryKey(Long seqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenericLog record, @Param("example") GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GenericLog record, @Param("example") GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenericLog record, @Param("example") GenericLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenericLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GenericLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenericLog record);
}