package com.example.migration.dao.master.mapper;

import com.example.migration.dao.master.entity.InstrumentVersion;
import com.example.migration.dao.master.entity.InstrumentVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InstrumentVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    long countByExample(InstrumentVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    int deleteByExample(InstrumentVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    int insert(InstrumentVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    int insertSelective(InstrumentVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    List<InstrumentVersion> selectByExampleWithRowbounds(InstrumentVersionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    List<InstrumentVersion> selectByExample(InstrumentVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InstrumentVersion record, @Param("example") InstrumentVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InstrumentVersion record, @Param("example") InstrumentVersionExample example);
}