package com.example.migration.dao.master.mapper;

import com.example.migration.dao.master.entity.InstrumentExtVersion;
import com.example.migration.dao.master.entity.InstrumentExtVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InstrumentExtVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    long countByExample(InstrumentExtVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    int deleteByExample(InstrumentExtVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    int insert(InstrumentExtVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    int insertSelective(InstrumentExtVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    List<InstrumentExtVersion> selectByExampleWithRowbounds(InstrumentExtVersionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    List<InstrumentExtVersion> selectByExample(InstrumentExtVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InstrumentExtVersion record, @Param("example") InstrumentExtVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InstrumentExtVersion record, @Param("example") InstrumentExtVersionExample example);
}