package com.example.migration.dao.master.mapper;

import com.example.migration.dao.master.entity.TTLMarketBoard;
import com.example.migration.dao.master.entity.TTLMarketBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TTLMarketBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    long countByExample(TTLMarketBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int deleteByExample(TTLMarketBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String market);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int insert(TTLMarketBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int insertSelective(TTLMarketBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    List<TTLMarketBoard> selectByExampleWithRowbounds(TTLMarketBoardExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    List<TTLMarketBoard> selectByExample(TTLMarketBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    TTLMarketBoard selectByPrimaryKey(String market);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTLMarketBoard record, @Param("example") TTLMarketBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTLMarketBoard record, @Param("example") TTLMarketBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTLMarketBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTLMarketBoard record);
}