package com.example.migration.dao.master.mapper;

import com.example.migration.dao.master.entity.TTLMQOrders;
import com.example.migration.dao.master.entity.TTLMQOrdersExample;
import com.example.migration.dao.master.entity.TTLMQOrdersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TTLMQOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    long countByExample(TTLMQOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int deleteByExample(TTLMQOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TTLMQOrdersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int insert(TTLMQOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int insertSelective(TTLMQOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    List<TTLMQOrders> selectByExampleWithRowbounds(TTLMQOrdersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    List<TTLMQOrders> selectByExample(TTLMQOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    TTLMQOrders selectByPrimaryKey(TTLMQOrdersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTLMQOrders record, @Param("example") TTLMQOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTLMQOrders record, @Param("example") TTLMQOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTLMQOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTLMQOrders record);
}