package com.example.migration.dao.slave.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   代码生成表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table gen_table
 */
public class GenTable implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   表名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     * Database Column Remarks:
     *   类名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     * Database Column Remarks:
     *   数据库类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.db_type
     *
     * @mbg.generated
     */
    private String dbType;

    /**
     * Database Column Remarks:
     *   说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.table_comment
     *
     * @mbg.generated
     */
    private String tableComment;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   项目包名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.package_name
     *
     * @mbg.generated
     */
    private String packageName;

    /**
     * Database Column Remarks:
     *   项目版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     * Database Column Remarks:
     *   是否生成带有i18n 0 不带有 1带有
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.i18n
     *
     * @mbg.generated
     */
    private String i18n;

    /**
     * Database Column Remarks:
     *   代码风格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     * Database Column Remarks:
     *   子表名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.child_table_name
     *
     * @mbg.generated
     */
    private String childTableName;

    /**
     * Database Column Remarks:
     *   主表关联键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.main_field
     *
     * @mbg.generated
     */
    private String mainField;

    /**
     * Database Column Remarks:
     *   子表关联键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.child_field
     *
     * @mbg.generated
     */
    private String childField;

    /**
     * Database Column Remarks:
     *   生成方式  0：zip压缩包   1：自定义目录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.generator_type
     *
     * @mbg.generated
     */
    private String generatorType;

    /**
     * Database Column Remarks:
     *   后端生成路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.backend_path
     *
     * @mbg.generated
     */
    private String backendPath;

    /**
     * Database Column Remarks:
     *   前端生成路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.frontend_path
     *
     * @mbg.generated
     */
    private String frontendPath;

    /**
     * Database Column Remarks:
     *   模块名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     * Database Column Remarks:
     *   功能名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.function_name
     *
     * @mbg.generated
     */
    private String functionName;

    /**
     * Database Column Remarks:
     *   表单布局  1：一列   2：两列
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.form_layout
     *
     * @mbg.generated
     */
    private Byte formLayout;

    /**
     * Database Column Remarks:
     *   数据源ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.ds_name
     *
     * @mbg.generated
     */
    private String dsName;

    /**
     * Database Column Remarks:
     *   基类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.baseclass_id
     *
     * @mbg.generated
     */
    private Long baseclassId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_table.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.id
     *
     * @return the value of gen_table.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.id
     *
     * @param id the value for gen_table.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.table_name
     *
     * @return the value of gen_table.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.table_name
     *
     * @param tableName the value for gen_table.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.class_name
     *
     * @return the value of gen_table.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.class_name
     *
     * @param className the value for gen_table.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.db_type
     *
     * @return the value of gen_table.db_type
     *
     * @mbg.generated
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.db_type
     *
     * @param dbType the value for gen_table.db_type
     *
     * @mbg.generated
     */
    public void setDbType(String dbType) {
        this.dbType = dbType == null ? null : dbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.table_comment
     *
     * @return the value of gen_table.table_comment
     *
     * @mbg.generated
     */
    public String getTableComment() {
        return tableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.table_comment
     *
     * @param tableComment the value for gen_table.table_comment
     *
     * @mbg.generated
     */
    public void setTableComment(String tableComment) {
        this.tableComment = tableComment == null ? null : tableComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.author
     *
     * @return the value of gen_table.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.author
     *
     * @param author the value for gen_table.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.email
     *
     * @return the value of gen_table.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.email
     *
     * @param email the value for gen_table.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.package_name
     *
     * @return the value of gen_table.package_name
     *
     * @mbg.generated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.package_name
     *
     * @param packageName the value for gen_table.package_name
     *
     * @mbg.generated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.version
     *
     * @return the value of gen_table.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.version
     *
     * @param version the value for gen_table.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.i18n
     *
     * @return the value of gen_table.i18n
     *
     * @mbg.generated
     */
    public String getI18n() {
        return i18n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.i18n
     *
     * @param i18n the value for gen_table.i18n
     *
     * @mbg.generated
     */
    public void setI18n(String i18n) {
        this.i18n = i18n == null ? null : i18n.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.style
     *
     * @return the value of gen_table.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.style
     *
     * @param style the value for gen_table.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.child_table_name
     *
     * @return the value of gen_table.child_table_name
     *
     * @mbg.generated
     */
    public String getChildTableName() {
        return childTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.child_table_name
     *
     * @param childTableName the value for gen_table.child_table_name
     *
     * @mbg.generated
     */
    public void setChildTableName(String childTableName) {
        this.childTableName = childTableName == null ? null : childTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.main_field
     *
     * @return the value of gen_table.main_field
     *
     * @mbg.generated
     */
    public String getMainField() {
        return mainField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.main_field
     *
     * @param mainField the value for gen_table.main_field
     *
     * @mbg.generated
     */
    public void setMainField(String mainField) {
        this.mainField = mainField == null ? null : mainField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.child_field
     *
     * @return the value of gen_table.child_field
     *
     * @mbg.generated
     */
    public String getChildField() {
        return childField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.child_field
     *
     * @param childField the value for gen_table.child_field
     *
     * @mbg.generated
     */
    public void setChildField(String childField) {
        this.childField = childField == null ? null : childField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.generator_type
     *
     * @return the value of gen_table.generator_type
     *
     * @mbg.generated
     */
    public String getGeneratorType() {
        return generatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.generator_type
     *
     * @param generatorType the value for gen_table.generator_type
     *
     * @mbg.generated
     */
    public void setGeneratorType(String generatorType) {
        this.generatorType = generatorType == null ? null : generatorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.backend_path
     *
     * @return the value of gen_table.backend_path
     *
     * @mbg.generated
     */
    public String getBackendPath() {
        return backendPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.backend_path
     *
     * @param backendPath the value for gen_table.backend_path
     *
     * @mbg.generated
     */
    public void setBackendPath(String backendPath) {
        this.backendPath = backendPath == null ? null : backendPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.frontend_path
     *
     * @return the value of gen_table.frontend_path
     *
     * @mbg.generated
     */
    public String getFrontendPath() {
        return frontendPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.frontend_path
     *
     * @param frontendPath the value for gen_table.frontend_path
     *
     * @mbg.generated
     */
    public void setFrontendPath(String frontendPath) {
        this.frontendPath = frontendPath == null ? null : frontendPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.module_name
     *
     * @return the value of gen_table.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.module_name
     *
     * @param moduleName the value for gen_table.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.function_name
     *
     * @return the value of gen_table.function_name
     *
     * @mbg.generated
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.function_name
     *
     * @param functionName the value for gen_table.function_name
     *
     * @mbg.generated
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.form_layout
     *
     * @return the value of gen_table.form_layout
     *
     * @mbg.generated
     */
    public Byte getFormLayout() {
        return formLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.form_layout
     *
     * @param formLayout the value for gen_table.form_layout
     *
     * @mbg.generated
     */
    public void setFormLayout(Byte formLayout) {
        this.formLayout = formLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.ds_name
     *
     * @return the value of gen_table.ds_name
     *
     * @mbg.generated
     */
    public String getDsName() {
        return dsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.ds_name
     *
     * @param dsName the value for gen_table.ds_name
     *
     * @mbg.generated
     */
    public void setDsName(String dsName) {
        this.dsName = dsName == null ? null : dsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.baseclass_id
     *
     * @return the value of gen_table.baseclass_id
     *
     * @mbg.generated
     */
    public Long getBaseclassId() {
        return baseclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.baseclass_id
     *
     * @param baseclassId the value for gen_table.baseclass_id
     *
     * @mbg.generated
     */
    public void setBaseclassId(Long baseclassId) {
        this.baseclassId = baseclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_table.create_time
     *
     * @return the value of gen_table.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_table.create_time
     *
     * @param createTime the value for gen_table.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GenTable other = (GenTable) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()))
            && (this.getClassName() == null ? other.getClassName() == null : this.getClassName().equals(other.getClassName()))
            && (this.getDbType() == null ? other.getDbType() == null : this.getDbType().equals(other.getDbType()))
            && (this.getTableComment() == null ? other.getTableComment() == null : this.getTableComment().equals(other.getTableComment()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPackageName() == null ? other.getPackageName() == null : this.getPackageName().equals(other.getPackageName()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getI18n() == null ? other.getI18n() == null : this.getI18n().equals(other.getI18n()))
            && (this.getStyle() == null ? other.getStyle() == null : this.getStyle().equals(other.getStyle()))
            && (this.getChildTableName() == null ? other.getChildTableName() == null : this.getChildTableName().equals(other.getChildTableName()))
            && (this.getMainField() == null ? other.getMainField() == null : this.getMainField().equals(other.getMainField()))
            && (this.getChildField() == null ? other.getChildField() == null : this.getChildField().equals(other.getChildField()))
            && (this.getGeneratorType() == null ? other.getGeneratorType() == null : this.getGeneratorType().equals(other.getGeneratorType()))
            && (this.getBackendPath() == null ? other.getBackendPath() == null : this.getBackendPath().equals(other.getBackendPath()))
            && (this.getFrontendPath() == null ? other.getFrontendPath() == null : this.getFrontendPath().equals(other.getFrontendPath()))
            && (this.getModuleName() == null ? other.getModuleName() == null : this.getModuleName().equals(other.getModuleName()))
            && (this.getFunctionName() == null ? other.getFunctionName() == null : this.getFunctionName().equals(other.getFunctionName()))
            && (this.getFormLayout() == null ? other.getFormLayout() == null : this.getFormLayout().equals(other.getFormLayout()))
            && (this.getDsName() == null ? other.getDsName() == null : this.getDsName().equals(other.getDsName()))
            && (this.getBaseclassId() == null ? other.getBaseclassId() == null : this.getBaseclassId().equals(other.getBaseclassId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        result = prime * result + ((getClassName() == null) ? 0 : getClassName().hashCode());
        result = prime * result + ((getDbType() == null) ? 0 : getDbType().hashCode());
        result = prime * result + ((getTableComment() == null) ? 0 : getTableComment().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPackageName() == null) ? 0 : getPackageName().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getI18n() == null) ? 0 : getI18n().hashCode());
        result = prime * result + ((getStyle() == null) ? 0 : getStyle().hashCode());
        result = prime * result + ((getChildTableName() == null) ? 0 : getChildTableName().hashCode());
        result = prime * result + ((getMainField() == null) ? 0 : getMainField().hashCode());
        result = prime * result + ((getChildField() == null) ? 0 : getChildField().hashCode());
        result = prime * result + ((getGeneratorType() == null) ? 0 : getGeneratorType().hashCode());
        result = prime * result + ((getBackendPath() == null) ? 0 : getBackendPath().hashCode());
        result = prime * result + ((getFrontendPath() == null) ? 0 : getFrontendPath().hashCode());
        result = prime * result + ((getModuleName() == null) ? 0 : getModuleName().hashCode());
        result = prime * result + ((getFunctionName() == null) ? 0 : getFunctionName().hashCode());
        result = prime * result + ((getFormLayout() == null) ? 0 : getFormLayout().hashCode());
        result = prime * result + ((getDsName() == null) ? 0 : getDsName().hashCode());
        result = prime * result + ((getBaseclassId() == null) ? 0 : getBaseclassId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tableName=").append(tableName);
        sb.append(", className=").append(className);
        sb.append(", dbType=").append(dbType);
        sb.append(", tableComment=").append(tableComment);
        sb.append(", author=").append(author);
        sb.append(", email=").append(email);
        sb.append(", packageName=").append(packageName);
        sb.append(", version=").append(version);
        sb.append(", i18n=").append(i18n);
        sb.append(", style=").append(style);
        sb.append(", childTableName=").append(childTableName);
        sb.append(", mainField=").append(mainField);
        sb.append(", childField=").append(childField);
        sb.append(", generatorType=").append(generatorType);
        sb.append(", backendPath=").append(backendPath);
        sb.append(", frontendPath=").append(frontendPath);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", functionName=").append(functionName);
        sb.append(", formLayout=").append(formLayout);
        sb.append(", dsName=").append(dsName);
        sb.append(", baseclassId=").append(baseclassId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}