package com.example.migration.dao.slave.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GenTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public GenTableExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("table_name is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("table_name is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("table_name =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("table_name <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("table_name >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("table_name >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("table_name <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("table_name <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("table_name like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("table_name not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("table_name in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("table_name not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("table_name between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("table_name not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andDbTypeIsNull() {
            addCriterion("db_type is null");
            return (Criteria) this;
        }

        public Criteria andDbTypeIsNotNull() {
            addCriterion("db_type is not null");
            return (Criteria) this;
        }

        public Criteria andDbTypeEqualTo(String value) {
            addCriterion("db_type =", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotEqualTo(String value) {
            addCriterion("db_type <>", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeGreaterThan(String value) {
            addCriterion("db_type >", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeGreaterThanOrEqualTo(String value) {
            addCriterion("db_type >=", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeLessThan(String value) {
            addCriterion("db_type <", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeLessThanOrEqualTo(String value) {
            addCriterion("db_type <=", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeLike(String value) {
            addCriterion("db_type like", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotLike(String value) {
            addCriterion("db_type not like", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeIn(List<String> values) {
            addCriterion("db_type in", values, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotIn(List<String> values) {
            addCriterion("db_type not in", values, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeBetween(String value1, String value2) {
            addCriterion("db_type between", value1, value2, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotBetween(String value1, String value2) {
            addCriterion("db_type not between", value1, value2, "dbType");
            return (Criteria) this;
        }

        public Criteria andTableCommentIsNull() {
            addCriterion("table_comment is null");
            return (Criteria) this;
        }

        public Criteria andTableCommentIsNotNull() {
            addCriterion("table_comment is not null");
            return (Criteria) this;
        }

        public Criteria andTableCommentEqualTo(String value) {
            addCriterion("table_comment =", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotEqualTo(String value) {
            addCriterion("table_comment <>", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentGreaterThan(String value) {
            addCriterion("table_comment >", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentGreaterThanOrEqualTo(String value) {
            addCriterion("table_comment >=", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentLessThan(String value) {
            addCriterion("table_comment <", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentLessThanOrEqualTo(String value) {
            addCriterion("table_comment <=", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentLike(String value) {
            addCriterion("table_comment like", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotLike(String value) {
            addCriterion("table_comment not like", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentIn(List<String> values) {
            addCriterion("table_comment in", values, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotIn(List<String> values) {
            addCriterion("table_comment not in", values, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentBetween(String value1, String value2) {
            addCriterion("table_comment between", value1, value2, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotBetween(String value1, String value2) {
            addCriterion("table_comment not between", value1, value2, "tableComment");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameIn(List<String> values) {
            addCriterion("package_name in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotIn(List<String> values) {
            addCriterion("package_name not in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andI18nIsNull() {
            addCriterion("i18n is null");
            return (Criteria) this;
        }

        public Criteria andI18nIsNotNull() {
            addCriterion("i18n is not null");
            return (Criteria) this;
        }

        public Criteria andI18nEqualTo(String value) {
            addCriterion("i18n =", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nNotEqualTo(String value) {
            addCriterion("i18n <>", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nGreaterThan(String value) {
            addCriterion("i18n >", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nGreaterThanOrEqualTo(String value) {
            addCriterion("i18n >=", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nLessThan(String value) {
            addCriterion("i18n <", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nLessThanOrEqualTo(String value) {
            addCriterion("i18n <=", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nLike(String value) {
            addCriterion("i18n like", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nNotLike(String value) {
            addCriterion("i18n not like", value, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nIn(List<String> values) {
            addCriterion("i18n in", values, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nNotIn(List<String> values) {
            addCriterion("i18n not in", values, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nBetween(String value1, String value2) {
            addCriterion("i18n between", value1, value2, "i18n");
            return (Criteria) this;
        }

        public Criteria andI18nNotBetween(String value1, String value2) {
            addCriterion("i18n not between", value1, value2, "i18n");
            return (Criteria) this;
        }

        public Criteria andStyleIsNull() {
            addCriterion("style is null");
            return (Criteria) this;
        }

        public Criteria andStyleIsNotNull() {
            addCriterion("style is not null");
            return (Criteria) this;
        }

        public Criteria andStyleEqualTo(String value) {
            addCriterion("style =", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotEqualTo(String value) {
            addCriterion("style <>", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThan(String value) {
            addCriterion("style >", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThanOrEqualTo(String value) {
            addCriterion("style >=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThan(String value) {
            addCriterion("style <", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThanOrEqualTo(String value) {
            addCriterion("style <=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLike(String value) {
            addCriterion("style like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotLike(String value) {
            addCriterion("style not like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleIn(List<String> values) {
            addCriterion("style in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotIn(List<String> values) {
            addCriterion("style not in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleBetween(String value1, String value2) {
            addCriterion("style between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotBetween(String value1, String value2) {
            addCriterion("style not between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andChildTableNameIsNull() {
            addCriterion("child_table_name is null");
            return (Criteria) this;
        }

        public Criteria andChildTableNameIsNotNull() {
            addCriterion("child_table_name is not null");
            return (Criteria) this;
        }

        public Criteria andChildTableNameEqualTo(String value) {
            addCriterion("child_table_name =", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameNotEqualTo(String value) {
            addCriterion("child_table_name <>", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameGreaterThan(String value) {
            addCriterion("child_table_name >", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("child_table_name >=", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameLessThan(String value) {
            addCriterion("child_table_name <", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameLessThanOrEqualTo(String value) {
            addCriterion("child_table_name <=", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameLike(String value) {
            addCriterion("child_table_name like", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameNotLike(String value) {
            addCriterion("child_table_name not like", value, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameIn(List<String> values) {
            addCriterion("child_table_name in", values, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameNotIn(List<String> values) {
            addCriterion("child_table_name not in", values, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameBetween(String value1, String value2) {
            addCriterion("child_table_name between", value1, value2, "childTableName");
            return (Criteria) this;
        }

        public Criteria andChildTableNameNotBetween(String value1, String value2) {
            addCriterion("child_table_name not between", value1, value2, "childTableName");
            return (Criteria) this;
        }

        public Criteria andMainFieldIsNull() {
            addCriterion("main_field is null");
            return (Criteria) this;
        }

        public Criteria andMainFieldIsNotNull() {
            addCriterion("main_field is not null");
            return (Criteria) this;
        }

        public Criteria andMainFieldEqualTo(String value) {
            addCriterion("main_field =", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldNotEqualTo(String value) {
            addCriterion("main_field <>", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldGreaterThan(String value) {
            addCriterion("main_field >", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldGreaterThanOrEqualTo(String value) {
            addCriterion("main_field >=", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldLessThan(String value) {
            addCriterion("main_field <", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldLessThanOrEqualTo(String value) {
            addCriterion("main_field <=", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldLike(String value) {
            addCriterion("main_field like", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldNotLike(String value) {
            addCriterion("main_field not like", value, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldIn(List<String> values) {
            addCriterion("main_field in", values, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldNotIn(List<String> values) {
            addCriterion("main_field not in", values, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldBetween(String value1, String value2) {
            addCriterion("main_field between", value1, value2, "mainField");
            return (Criteria) this;
        }

        public Criteria andMainFieldNotBetween(String value1, String value2) {
            addCriterion("main_field not between", value1, value2, "mainField");
            return (Criteria) this;
        }

        public Criteria andChildFieldIsNull() {
            addCriterion("child_field is null");
            return (Criteria) this;
        }

        public Criteria andChildFieldIsNotNull() {
            addCriterion("child_field is not null");
            return (Criteria) this;
        }

        public Criteria andChildFieldEqualTo(String value) {
            addCriterion("child_field =", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldNotEqualTo(String value) {
            addCriterion("child_field <>", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldGreaterThan(String value) {
            addCriterion("child_field >", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldGreaterThanOrEqualTo(String value) {
            addCriterion("child_field >=", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldLessThan(String value) {
            addCriterion("child_field <", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldLessThanOrEqualTo(String value) {
            addCriterion("child_field <=", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldLike(String value) {
            addCriterion("child_field like", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldNotLike(String value) {
            addCriterion("child_field not like", value, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldIn(List<String> values) {
            addCriterion("child_field in", values, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldNotIn(List<String> values) {
            addCriterion("child_field not in", values, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldBetween(String value1, String value2) {
            addCriterion("child_field between", value1, value2, "childField");
            return (Criteria) this;
        }

        public Criteria andChildFieldNotBetween(String value1, String value2) {
            addCriterion("child_field not between", value1, value2, "childField");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeIsNull() {
            addCriterion("generator_type is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeIsNotNull() {
            addCriterion("generator_type is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeEqualTo(String value) {
            addCriterion("generator_type =", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotEqualTo(String value) {
            addCriterion("generator_type <>", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeGreaterThan(String value) {
            addCriterion("generator_type >", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("generator_type >=", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeLessThan(String value) {
            addCriterion("generator_type <", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeLessThanOrEqualTo(String value) {
            addCriterion("generator_type <=", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeLike(String value) {
            addCriterion("generator_type like", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotLike(String value) {
            addCriterion("generator_type not like", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeIn(List<String> values) {
            addCriterion("generator_type in", values, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotIn(List<String> values) {
            addCriterion("generator_type not in", values, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeBetween(String value1, String value2) {
            addCriterion("generator_type between", value1, value2, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotBetween(String value1, String value2) {
            addCriterion("generator_type not between", value1, value2, "generatorType");
            return (Criteria) this;
        }

        public Criteria andBackendPathIsNull() {
            addCriterion("backend_path is null");
            return (Criteria) this;
        }

        public Criteria andBackendPathIsNotNull() {
            addCriterion("backend_path is not null");
            return (Criteria) this;
        }

        public Criteria andBackendPathEqualTo(String value) {
            addCriterion("backend_path =", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathNotEqualTo(String value) {
            addCriterion("backend_path <>", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathGreaterThan(String value) {
            addCriterion("backend_path >", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathGreaterThanOrEqualTo(String value) {
            addCriterion("backend_path >=", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathLessThan(String value) {
            addCriterion("backend_path <", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathLessThanOrEqualTo(String value) {
            addCriterion("backend_path <=", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathLike(String value) {
            addCriterion("backend_path like", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathNotLike(String value) {
            addCriterion("backend_path not like", value, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathIn(List<String> values) {
            addCriterion("backend_path in", values, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathNotIn(List<String> values) {
            addCriterion("backend_path not in", values, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathBetween(String value1, String value2) {
            addCriterion("backend_path between", value1, value2, "backendPath");
            return (Criteria) this;
        }

        public Criteria andBackendPathNotBetween(String value1, String value2) {
            addCriterion("backend_path not between", value1, value2, "backendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathIsNull() {
            addCriterion("frontend_path is null");
            return (Criteria) this;
        }

        public Criteria andFrontendPathIsNotNull() {
            addCriterion("frontend_path is not null");
            return (Criteria) this;
        }

        public Criteria andFrontendPathEqualTo(String value) {
            addCriterion("frontend_path =", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathNotEqualTo(String value) {
            addCriterion("frontend_path <>", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathGreaterThan(String value) {
            addCriterion("frontend_path >", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathGreaterThanOrEqualTo(String value) {
            addCriterion("frontend_path >=", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathLessThan(String value) {
            addCriterion("frontend_path <", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathLessThanOrEqualTo(String value) {
            addCriterion("frontend_path <=", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathLike(String value) {
            addCriterion("frontend_path like", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathNotLike(String value) {
            addCriterion("frontend_path not like", value, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathIn(List<String> values) {
            addCriterion("frontend_path in", values, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathNotIn(List<String> values) {
            addCriterion("frontend_path not in", values, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathBetween(String value1, String value2) {
            addCriterion("frontend_path between", value1, value2, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathNotBetween(String value1, String value2) {
            addCriterion("frontend_path not between", value1, value2, "frontendPath");
            return (Criteria) this;
        }

        public Criteria andModuleNameIsNull() {
            addCriterion("module_name is null");
            return (Criteria) this;
        }

        public Criteria andModuleNameIsNotNull() {
            addCriterion("module_name is not null");
            return (Criteria) this;
        }

        public Criteria andModuleNameEqualTo(String value) {
            addCriterion("module_name =", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotEqualTo(String value) {
            addCriterion("module_name <>", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameGreaterThan(String value) {
            addCriterion("module_name >", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameGreaterThanOrEqualTo(String value) {
            addCriterion("module_name >=", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLessThan(String value) {
            addCriterion("module_name <", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLessThanOrEqualTo(String value) {
            addCriterion("module_name <=", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLike(String value) {
            addCriterion("module_name like", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotLike(String value) {
            addCriterion("module_name not like", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameIn(List<String> values) {
            addCriterion("module_name in", values, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotIn(List<String> values) {
            addCriterion("module_name not in", values, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameBetween(String value1, String value2) {
            addCriterion("module_name between", value1, value2, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotBetween(String value1, String value2) {
            addCriterion("module_name not between", value1, value2, "moduleName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNull() {
            addCriterion("function_name is null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNotNull() {
            addCriterion("function_name is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameEqualTo(String value) {
            addCriterion("function_name =", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotEqualTo(String value) {
            addCriterion("function_name <>", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThan(String value) {
            addCriterion("function_name >", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThanOrEqualTo(String value) {
            addCriterion("function_name >=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThan(String value) {
            addCriterion("function_name <", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThanOrEqualTo(String value) {
            addCriterion("function_name <=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLike(String value) {
            addCriterion("function_name like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotLike(String value) {
            addCriterion("function_name not like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIn(List<String> values) {
            addCriterion("function_name in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotIn(List<String> values) {
            addCriterion("function_name not in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameBetween(String value1, String value2) {
            addCriterion("function_name between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotBetween(String value1, String value2) {
            addCriterion("function_name not between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andFormLayoutIsNull() {
            addCriterion("form_layout is null");
            return (Criteria) this;
        }

        public Criteria andFormLayoutIsNotNull() {
            addCriterion("form_layout is not null");
            return (Criteria) this;
        }

        public Criteria andFormLayoutEqualTo(Byte value) {
            addCriterion("form_layout =", value, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutNotEqualTo(Byte value) {
            addCriterion("form_layout <>", value, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutGreaterThan(Byte value) {
            addCriterion("form_layout >", value, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutGreaterThanOrEqualTo(Byte value) {
            addCriterion("form_layout >=", value, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutLessThan(Byte value) {
            addCriterion("form_layout <", value, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutLessThanOrEqualTo(Byte value) {
            addCriterion("form_layout <=", value, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutIn(List<Byte> values) {
            addCriterion("form_layout in", values, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutNotIn(List<Byte> values) {
            addCriterion("form_layout not in", values, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutBetween(Byte value1, Byte value2) {
            addCriterion("form_layout between", value1, value2, "formLayout");
            return (Criteria) this;
        }

        public Criteria andFormLayoutNotBetween(Byte value1, Byte value2) {
            addCriterion("form_layout not between", value1, value2, "formLayout");
            return (Criteria) this;
        }

        public Criteria andDsNameIsNull() {
            addCriterion("ds_name is null");
            return (Criteria) this;
        }

        public Criteria andDsNameIsNotNull() {
            addCriterion("ds_name is not null");
            return (Criteria) this;
        }

        public Criteria andDsNameEqualTo(String value) {
            addCriterion("ds_name =", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameNotEqualTo(String value) {
            addCriterion("ds_name <>", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameGreaterThan(String value) {
            addCriterion("ds_name >", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameGreaterThanOrEqualTo(String value) {
            addCriterion("ds_name >=", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameLessThan(String value) {
            addCriterion("ds_name <", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameLessThanOrEqualTo(String value) {
            addCriterion("ds_name <=", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameLike(String value) {
            addCriterion("ds_name like", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameNotLike(String value) {
            addCriterion("ds_name not like", value, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameIn(List<String> values) {
            addCriterion("ds_name in", values, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameNotIn(List<String> values) {
            addCriterion("ds_name not in", values, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameBetween(String value1, String value2) {
            addCriterion("ds_name between", value1, value2, "dsName");
            return (Criteria) this;
        }

        public Criteria andDsNameNotBetween(String value1, String value2) {
            addCriterion("ds_name not between", value1, value2, "dsName");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdIsNull() {
            addCriterion("baseclass_id is null");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdIsNotNull() {
            addCriterion("baseclass_id is not null");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdEqualTo(Long value) {
            addCriterion("baseclass_id =", value, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdNotEqualTo(Long value) {
            addCriterion("baseclass_id <>", value, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdGreaterThan(Long value) {
            addCriterion("baseclass_id >", value, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdGreaterThanOrEqualTo(Long value) {
            addCriterion("baseclass_id >=", value, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdLessThan(Long value) {
            addCriterion("baseclass_id <", value, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdLessThanOrEqualTo(Long value) {
            addCriterion("baseclass_id <=", value, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdIn(List<Long> values) {
            addCriterion("baseclass_id in", values, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdNotIn(List<Long> values) {
            addCriterion("baseclass_id not in", values, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdBetween(Long value1, Long value2) {
            addCriterion("baseclass_id between", value1, value2, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andBaseclassIdNotBetween(Long value1, Long value2) {
            addCriterion("baseclass_id not between", value1, value2, "baseclassId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andTableNameLikeInsensitive(String value) {
            addCriterion("upper(table_name) like", value.toUpperCase(), "tableName");
            return (Criteria) this;
        }

        public Criteria andClassNameLikeInsensitive(String value) {
            addCriterion("upper(class_name) like", value.toUpperCase(), "className");
            return (Criteria) this;
        }

        public Criteria andDbTypeLikeInsensitive(String value) {
            addCriterion("upper(db_type) like", value.toUpperCase(), "dbType");
            return (Criteria) this;
        }

        public Criteria andTableCommentLikeInsensitive(String value) {
            addCriterion("upper(table_comment) like", value.toUpperCase(), "tableComment");
            return (Criteria) this;
        }

        public Criteria andAuthorLikeInsensitive(String value) {
            addCriterion("upper(author) like", value.toUpperCase(), "author");
            return (Criteria) this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("upper(email) like", value.toUpperCase(), "email");
            return (Criteria) this;
        }

        public Criteria andPackageNameLikeInsensitive(String value) {
            addCriterion("upper(package_name) like", value.toUpperCase(), "packageName");
            return (Criteria) this;
        }

        public Criteria andVersionLikeInsensitive(String value) {
            addCriterion("upper(version) like", value.toUpperCase(), "version");
            return (Criteria) this;
        }

        public Criteria andI18nLikeInsensitive(String value) {
            addCriterion("upper(i18n) like", value.toUpperCase(), "i18n");
            return (Criteria) this;
        }

        public Criteria andStyleLikeInsensitive(String value) {
            addCriterion("upper(style) like", value.toUpperCase(), "style");
            return (Criteria) this;
        }

        public Criteria andChildTableNameLikeInsensitive(String value) {
            addCriterion("upper(child_table_name) like", value.toUpperCase(), "childTableName");
            return (Criteria) this;
        }

        public Criteria andMainFieldLikeInsensitive(String value) {
            addCriterion("upper(main_field) like", value.toUpperCase(), "mainField");
            return (Criteria) this;
        }

        public Criteria andChildFieldLikeInsensitive(String value) {
            addCriterion("upper(child_field) like", value.toUpperCase(), "childField");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeLikeInsensitive(String value) {
            addCriterion("upper(generator_type) like", value.toUpperCase(), "generatorType");
            return (Criteria) this;
        }

        public Criteria andBackendPathLikeInsensitive(String value) {
            addCriterion("upper(backend_path) like", value.toUpperCase(), "backendPath");
            return (Criteria) this;
        }

        public Criteria andFrontendPathLikeInsensitive(String value) {
            addCriterion("upper(frontend_path) like", value.toUpperCase(), "frontendPath");
            return (Criteria) this;
        }

        public Criteria andModuleNameLikeInsensitive(String value) {
            addCriterion("upper(module_name) like", value.toUpperCase(), "moduleName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLikeInsensitive(String value) {
            addCriterion("upper(function_name) like", value.toUpperCase(), "functionName");
            return (Criteria) this;
        }

        public Criteria andDsNameLikeInsensitive(String value) {
            addCriterion("upper(ds_name) like", value.toUpperCase(), "dsName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gen_table
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gen_table
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}