package com.example.migration.dao.master.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CMS_VIEW
 */
public class CmsView implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_VIEW.accountcode
     *
     * @mbg.generated
     */
    private String accountcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_VIEW.defaulttradingacc
     *
     * @mbg.generated
     */
    private String defaulttradingacc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_VIEW.accountcode
     *
     * @return the value of CMS_VIEW.accountcode
     *
     * @mbg.generated
     */
    public String getAccountcode() {
        return accountcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_VIEW.accountcode
     *
     * @param accountcode the value for CMS_VIEW.accountcode
     *
     * @mbg.generated
     */
    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode == null ? null : accountcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_VIEW.defaulttradingacc
     *
     * @return the value of CMS_VIEW.defaulttradingacc
     *
     * @mbg.generated
     */
    public String getDefaulttradingacc() {
        return defaulttradingacc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_VIEW.defaulttradingacc
     *
     * @param defaulttradingacc the value for CMS_VIEW.defaulttradingacc
     *
     * @mbg.generated
     */
    public void setDefaulttradingacc(String defaulttradingacc) {
        this.defaulttradingacc = defaulttradingacc == null ? null : defaulttradingacc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsView other = (CmsView) that;
        return (this.getAccountcode() == null ? other.getAccountcode() == null : this.getAccountcode().equals(other.getAccountcode()))
            && (this.getDefaulttradingacc() == null ? other.getDefaulttradingacc() == null : this.getDefaulttradingacc().equals(other.getDefaulttradingacc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAccountcode() == null) ? 0 : getAccountcode().hashCode());
        result = prime * result + ((getDefaulttradingacc() == null) ? 0 : getDefaulttradingacc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMS_VIEW
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", accountcode=").append(accountcode);
        sb.append(", defaulttradingacc=").append(defaulttradingacc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}