package com.example.migration.dao.master.entity;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table GenericLog
 */
public class GenericLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.SeqNo
     *
     * @mbg.generated
     */
    private Long seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.LogTable
     *
     * @mbg.generated
     */
    private String logtable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey1
     *
     * @mbg.generated
     */
    private String tablekey1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey2
     *
     * @mbg.generated
     */
    private String tablekey2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey3
     *
     * @mbg.generated
     */
    private String tablekey3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey4
     *
     * @mbg.generated
     */
    private String tablekey4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey5
     *
     * @mbg.generated
     */
    private String tablekey5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey6
     *
     * @mbg.generated
     */
    private String tablekey6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.TableKey7
     *
     * @mbg.generated
     */
    private String tablekey7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.LogColumn
     *
     * @mbg.generated
     */
    private String logcolumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.LogAction
     *
     * @mbg.generated
     */
    private String logaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.FieldDescription
     *
     * @mbg.generated
     */
    private String fielddescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.BeforeValue
     *
     * @mbg.generated
     */
    private String beforevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.AfterValue
     *
     * @mbg.generated
     */
    private String aftervalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.LogDateTime
     *
     * @mbg.generated
     */
    private Date logdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.LogHostName
     *
     * @mbg.generated
     */
    private String loghostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.LogUserName
     *
     * @mbg.generated
     */
    private String logusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GenericLog.timestamp
     *
     * @mbg.generated
     */
    private byte[] timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.SeqNo
     *
     * @return the value of GenericLog.SeqNo
     *
     * @mbg.generated
     */
    public Long getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.SeqNo
     *
     * @param seqno the value for GenericLog.SeqNo
     *
     * @mbg.generated
     */
    public void setSeqno(Long seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.LogTable
     *
     * @return the value of GenericLog.LogTable
     *
     * @mbg.generated
     */
    public String getLogtable() {
        return logtable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.LogTable
     *
     * @param logtable the value for GenericLog.LogTable
     *
     * @mbg.generated
     */
    public void setLogtable(String logtable) {
        this.logtable = logtable == null ? null : logtable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey1
     *
     * @return the value of GenericLog.TableKey1
     *
     * @mbg.generated
     */
    public String getTablekey1() {
        return tablekey1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey1
     *
     * @param tablekey1 the value for GenericLog.TableKey1
     *
     * @mbg.generated
     */
    public void setTablekey1(String tablekey1) {
        this.tablekey1 = tablekey1 == null ? null : tablekey1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey2
     *
     * @return the value of GenericLog.TableKey2
     *
     * @mbg.generated
     */
    public String getTablekey2() {
        return tablekey2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey2
     *
     * @param tablekey2 the value for GenericLog.TableKey2
     *
     * @mbg.generated
     */
    public void setTablekey2(String tablekey2) {
        this.tablekey2 = tablekey2 == null ? null : tablekey2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey3
     *
     * @return the value of GenericLog.TableKey3
     *
     * @mbg.generated
     */
    public String getTablekey3() {
        return tablekey3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey3
     *
     * @param tablekey3 the value for GenericLog.TableKey3
     *
     * @mbg.generated
     */
    public void setTablekey3(String tablekey3) {
        this.tablekey3 = tablekey3 == null ? null : tablekey3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey4
     *
     * @return the value of GenericLog.TableKey4
     *
     * @mbg.generated
     */
    public String getTablekey4() {
        return tablekey4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey4
     *
     * @param tablekey4 the value for GenericLog.TableKey4
     *
     * @mbg.generated
     */
    public void setTablekey4(String tablekey4) {
        this.tablekey4 = tablekey4 == null ? null : tablekey4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey5
     *
     * @return the value of GenericLog.TableKey5
     *
     * @mbg.generated
     */
    public String getTablekey5() {
        return tablekey5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey5
     *
     * @param tablekey5 the value for GenericLog.TableKey5
     *
     * @mbg.generated
     */
    public void setTablekey5(String tablekey5) {
        this.tablekey5 = tablekey5 == null ? null : tablekey5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey6
     *
     * @return the value of GenericLog.TableKey6
     *
     * @mbg.generated
     */
    public String getTablekey6() {
        return tablekey6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey6
     *
     * @param tablekey6 the value for GenericLog.TableKey6
     *
     * @mbg.generated
     */
    public void setTablekey6(String tablekey6) {
        this.tablekey6 = tablekey6 == null ? null : tablekey6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.TableKey7
     *
     * @return the value of GenericLog.TableKey7
     *
     * @mbg.generated
     */
    public String getTablekey7() {
        return tablekey7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.TableKey7
     *
     * @param tablekey7 the value for GenericLog.TableKey7
     *
     * @mbg.generated
     */
    public void setTablekey7(String tablekey7) {
        this.tablekey7 = tablekey7 == null ? null : tablekey7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.LogColumn
     *
     * @return the value of GenericLog.LogColumn
     *
     * @mbg.generated
     */
    public String getLogcolumn() {
        return logcolumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.LogColumn
     *
     * @param logcolumn the value for GenericLog.LogColumn
     *
     * @mbg.generated
     */
    public void setLogcolumn(String logcolumn) {
        this.logcolumn = logcolumn == null ? null : logcolumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.LogAction
     *
     * @return the value of GenericLog.LogAction
     *
     * @mbg.generated
     */
    public String getLogaction() {
        return logaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.LogAction
     *
     * @param logaction the value for GenericLog.LogAction
     *
     * @mbg.generated
     */
    public void setLogaction(String logaction) {
        this.logaction = logaction == null ? null : logaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.FieldDescription
     *
     * @return the value of GenericLog.FieldDescription
     *
     * @mbg.generated
     */
    public String getFielddescription() {
        return fielddescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.FieldDescription
     *
     * @param fielddescription the value for GenericLog.FieldDescription
     *
     * @mbg.generated
     */
    public void setFielddescription(String fielddescription) {
        this.fielddescription = fielddescription == null ? null : fielddescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.BeforeValue
     *
     * @return the value of GenericLog.BeforeValue
     *
     * @mbg.generated
     */
    public String getBeforevalue() {
        return beforevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.BeforeValue
     *
     * @param beforevalue the value for GenericLog.BeforeValue
     *
     * @mbg.generated
     */
    public void setBeforevalue(String beforevalue) {
        this.beforevalue = beforevalue == null ? null : beforevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.AfterValue
     *
     * @return the value of GenericLog.AfterValue
     *
     * @mbg.generated
     */
    public String getAftervalue() {
        return aftervalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.AfterValue
     *
     * @param aftervalue the value for GenericLog.AfterValue
     *
     * @mbg.generated
     */
    public void setAftervalue(String aftervalue) {
        this.aftervalue = aftervalue == null ? null : aftervalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.LogDateTime
     *
     * @return the value of GenericLog.LogDateTime
     *
     * @mbg.generated
     */
    public Date getLogdatetime() {
        return logdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.LogDateTime
     *
     * @param logdatetime the value for GenericLog.LogDateTime
     *
     * @mbg.generated
     */
    public void setLogdatetime(Date logdatetime) {
        this.logdatetime = logdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.LogHostName
     *
     * @return the value of GenericLog.LogHostName
     *
     * @mbg.generated
     */
    public String getLoghostname() {
        return loghostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.LogHostName
     *
     * @param loghostname the value for GenericLog.LogHostName
     *
     * @mbg.generated
     */
    public void setLoghostname(String loghostname) {
        this.loghostname = loghostname == null ? null : loghostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.LogUserName
     *
     * @return the value of GenericLog.LogUserName
     *
     * @mbg.generated
     */
    public String getLogusername() {
        return logusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.LogUserName
     *
     * @param logusername the value for GenericLog.LogUserName
     *
     * @mbg.generated
     */
    public void setLogusername(String logusername) {
        this.logusername = logusername == null ? null : logusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GenericLog.timestamp
     *
     * @return the value of GenericLog.timestamp
     *
     * @mbg.generated
     */
    public byte[] getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GenericLog.timestamp
     *
     * @param timestamp the value for GenericLog.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(byte[] timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GenericLog other = (GenericLog) that;
        return (this.getSeqno() == null ? other.getSeqno() == null : this.getSeqno().equals(other.getSeqno()))
            && (this.getLogtable() == null ? other.getLogtable() == null : this.getLogtable().equals(other.getLogtable()))
            && (this.getTablekey1() == null ? other.getTablekey1() == null : this.getTablekey1().equals(other.getTablekey1()))
            && (this.getTablekey2() == null ? other.getTablekey2() == null : this.getTablekey2().equals(other.getTablekey2()))
            && (this.getTablekey3() == null ? other.getTablekey3() == null : this.getTablekey3().equals(other.getTablekey3()))
            && (this.getTablekey4() == null ? other.getTablekey4() == null : this.getTablekey4().equals(other.getTablekey4()))
            && (this.getTablekey5() == null ? other.getTablekey5() == null : this.getTablekey5().equals(other.getTablekey5()))
            && (this.getTablekey6() == null ? other.getTablekey6() == null : this.getTablekey6().equals(other.getTablekey6()))
            && (this.getTablekey7() == null ? other.getTablekey7() == null : this.getTablekey7().equals(other.getTablekey7()))
            && (this.getLogcolumn() == null ? other.getLogcolumn() == null : this.getLogcolumn().equals(other.getLogcolumn()))
            && (this.getLogaction() == null ? other.getLogaction() == null : this.getLogaction().equals(other.getLogaction()))
            && (this.getFielddescription() == null ? other.getFielddescription() == null : this.getFielddescription().equals(other.getFielddescription()))
            && (this.getBeforevalue() == null ? other.getBeforevalue() == null : this.getBeforevalue().equals(other.getBeforevalue()))
            && (this.getAftervalue() == null ? other.getAftervalue() == null : this.getAftervalue().equals(other.getAftervalue()))
            && (this.getLogdatetime() == null ? other.getLogdatetime() == null : this.getLogdatetime().equals(other.getLogdatetime()))
            && (this.getLoghostname() == null ? other.getLoghostname() == null : this.getLoghostname().equals(other.getLoghostname()))
            && (this.getLogusername() == null ? other.getLogusername() == null : this.getLogusername().equals(other.getLogusername()))
            && (Arrays.equals(this.getTimestamp(), other.getTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqno() == null) ? 0 : getSeqno().hashCode());
        result = prime * result + ((getLogtable() == null) ? 0 : getLogtable().hashCode());
        result = prime * result + ((getTablekey1() == null) ? 0 : getTablekey1().hashCode());
        result = prime * result + ((getTablekey2() == null) ? 0 : getTablekey2().hashCode());
        result = prime * result + ((getTablekey3() == null) ? 0 : getTablekey3().hashCode());
        result = prime * result + ((getTablekey4() == null) ? 0 : getTablekey4().hashCode());
        result = prime * result + ((getTablekey5() == null) ? 0 : getTablekey5().hashCode());
        result = prime * result + ((getTablekey6() == null) ? 0 : getTablekey6().hashCode());
        result = prime * result + ((getTablekey7() == null) ? 0 : getTablekey7().hashCode());
        result = prime * result + ((getLogcolumn() == null) ? 0 : getLogcolumn().hashCode());
        result = prime * result + ((getLogaction() == null) ? 0 : getLogaction().hashCode());
        result = prime * result + ((getFielddescription() == null) ? 0 : getFielddescription().hashCode());
        result = prime * result + ((getBeforevalue() == null) ? 0 : getBeforevalue().hashCode());
        result = prime * result + ((getAftervalue() == null) ? 0 : getAftervalue().hashCode());
        result = prime * result + ((getLogdatetime() == null) ? 0 : getLogdatetime().hashCode());
        result = prime * result + ((getLoghostname() == null) ? 0 : getLoghostname().hashCode());
        result = prime * result + ((getLogusername() == null) ? 0 : getLogusername().hashCode());
        result = prime * result + (Arrays.hashCode(getTimestamp()));
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqno=").append(seqno);
        sb.append(", logtable=").append(logtable);
        sb.append(", tablekey1=").append(tablekey1);
        sb.append(", tablekey2=").append(tablekey2);
        sb.append(", tablekey3=").append(tablekey3);
        sb.append(", tablekey4=").append(tablekey4);
        sb.append(", tablekey5=").append(tablekey5);
        sb.append(", tablekey6=").append(tablekey6);
        sb.append(", tablekey7=").append(tablekey7);
        sb.append(", logcolumn=").append(logcolumn);
        sb.append(", logaction=").append(logaction);
        sb.append(", fielddescription=").append(fielddescription);
        sb.append(", beforevalue=").append(beforevalue);
        sb.append(", aftervalue=").append(aftervalue);
        sb.append(", logdatetime=").append(logdatetime);
        sb.append(", loghostname=").append(loghostname);
        sb.append(", logusername=").append(logusername);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}