package com.example.migration.dao.master.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GenericLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public GenericLogExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("SeqNo is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("SeqNo is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(Long value) {
            addCriterion("SeqNo =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(Long value) {
            addCriterion("SeqNo <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(Long value) {
            addCriterion("SeqNo >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(Long value) {
            addCriterion("SeqNo >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(Long value) {
            addCriterion("SeqNo <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(Long value) {
            addCriterion("SeqNo <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<Long> values) {
            addCriterion("SeqNo in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<Long> values) {
            addCriterion("SeqNo not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(Long value1, Long value2) {
            addCriterion("SeqNo between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(Long value1, Long value2) {
            addCriterion("SeqNo not between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andLogtableIsNull() {
            addCriterion("LogTable is null");
            return (Criteria) this;
        }

        public Criteria andLogtableIsNotNull() {
            addCriterion("LogTable is not null");
            return (Criteria) this;
        }

        public Criteria andLogtableEqualTo(String value) {
            addCriterion("LogTable =", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableNotEqualTo(String value) {
            addCriterion("LogTable <>", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableGreaterThan(String value) {
            addCriterion("LogTable >", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableGreaterThanOrEqualTo(String value) {
            addCriterion("LogTable >=", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableLessThan(String value) {
            addCriterion("LogTable <", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableLessThanOrEqualTo(String value) {
            addCriterion("LogTable <=", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableLike(String value) {
            addCriterion("LogTable like", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableNotLike(String value) {
            addCriterion("LogTable not like", value, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableIn(List<String> values) {
            addCriterion("LogTable in", values, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableNotIn(List<String> values) {
            addCriterion("LogTable not in", values, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableBetween(String value1, String value2) {
            addCriterion("LogTable between", value1, value2, "logtable");
            return (Criteria) this;
        }

        public Criteria andLogtableNotBetween(String value1, String value2) {
            addCriterion("LogTable not between", value1, value2, "logtable");
            return (Criteria) this;
        }

        public Criteria andTablekey1IsNull() {
            addCriterion("TableKey1 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey1IsNotNull() {
            addCriterion("TableKey1 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey1EqualTo(String value) {
            addCriterion("TableKey1 =", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1NotEqualTo(String value) {
            addCriterion("TableKey1 <>", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1GreaterThan(String value) {
            addCriterion("TableKey1 >", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey1 >=", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1LessThan(String value) {
            addCriterion("TableKey1 <", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1LessThanOrEqualTo(String value) {
            addCriterion("TableKey1 <=", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1Like(String value) {
            addCriterion("TableKey1 like", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1NotLike(String value) {
            addCriterion("TableKey1 not like", value, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1In(List<String> values) {
            addCriterion("TableKey1 in", values, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1NotIn(List<String> values) {
            addCriterion("TableKey1 not in", values, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1Between(String value1, String value2) {
            addCriterion("TableKey1 between", value1, value2, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey1NotBetween(String value1, String value2) {
            addCriterion("TableKey1 not between", value1, value2, "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey2IsNull() {
            addCriterion("TableKey2 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey2IsNotNull() {
            addCriterion("TableKey2 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey2EqualTo(String value) {
            addCriterion("TableKey2 =", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2NotEqualTo(String value) {
            addCriterion("TableKey2 <>", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2GreaterThan(String value) {
            addCriterion("TableKey2 >", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey2 >=", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2LessThan(String value) {
            addCriterion("TableKey2 <", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2LessThanOrEqualTo(String value) {
            addCriterion("TableKey2 <=", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2Like(String value) {
            addCriterion("TableKey2 like", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2NotLike(String value) {
            addCriterion("TableKey2 not like", value, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2In(List<String> values) {
            addCriterion("TableKey2 in", values, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2NotIn(List<String> values) {
            addCriterion("TableKey2 not in", values, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2Between(String value1, String value2) {
            addCriterion("TableKey2 between", value1, value2, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey2NotBetween(String value1, String value2) {
            addCriterion("TableKey2 not between", value1, value2, "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey3IsNull() {
            addCriterion("TableKey3 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey3IsNotNull() {
            addCriterion("TableKey3 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey3EqualTo(String value) {
            addCriterion("TableKey3 =", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3NotEqualTo(String value) {
            addCriterion("TableKey3 <>", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3GreaterThan(String value) {
            addCriterion("TableKey3 >", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey3 >=", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3LessThan(String value) {
            addCriterion("TableKey3 <", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3LessThanOrEqualTo(String value) {
            addCriterion("TableKey3 <=", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3Like(String value) {
            addCriterion("TableKey3 like", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3NotLike(String value) {
            addCriterion("TableKey3 not like", value, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3In(List<String> values) {
            addCriterion("TableKey3 in", values, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3NotIn(List<String> values) {
            addCriterion("TableKey3 not in", values, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3Between(String value1, String value2) {
            addCriterion("TableKey3 between", value1, value2, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey3NotBetween(String value1, String value2) {
            addCriterion("TableKey3 not between", value1, value2, "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey4IsNull() {
            addCriterion("TableKey4 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey4IsNotNull() {
            addCriterion("TableKey4 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey4EqualTo(String value) {
            addCriterion("TableKey4 =", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4NotEqualTo(String value) {
            addCriterion("TableKey4 <>", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4GreaterThan(String value) {
            addCriterion("TableKey4 >", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey4 >=", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4LessThan(String value) {
            addCriterion("TableKey4 <", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4LessThanOrEqualTo(String value) {
            addCriterion("TableKey4 <=", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4Like(String value) {
            addCriterion("TableKey4 like", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4NotLike(String value) {
            addCriterion("TableKey4 not like", value, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4In(List<String> values) {
            addCriterion("TableKey4 in", values, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4NotIn(List<String> values) {
            addCriterion("TableKey4 not in", values, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4Between(String value1, String value2) {
            addCriterion("TableKey4 between", value1, value2, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey4NotBetween(String value1, String value2) {
            addCriterion("TableKey4 not between", value1, value2, "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey5IsNull() {
            addCriterion("TableKey5 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey5IsNotNull() {
            addCriterion("TableKey5 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey5EqualTo(String value) {
            addCriterion("TableKey5 =", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5NotEqualTo(String value) {
            addCriterion("TableKey5 <>", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5GreaterThan(String value) {
            addCriterion("TableKey5 >", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey5 >=", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5LessThan(String value) {
            addCriterion("TableKey5 <", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5LessThanOrEqualTo(String value) {
            addCriterion("TableKey5 <=", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5Like(String value) {
            addCriterion("TableKey5 like", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5NotLike(String value) {
            addCriterion("TableKey5 not like", value, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5In(List<String> values) {
            addCriterion("TableKey5 in", values, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5NotIn(List<String> values) {
            addCriterion("TableKey5 not in", values, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5Between(String value1, String value2) {
            addCriterion("TableKey5 between", value1, value2, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey5NotBetween(String value1, String value2) {
            addCriterion("TableKey5 not between", value1, value2, "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey6IsNull() {
            addCriterion("TableKey6 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey6IsNotNull() {
            addCriterion("TableKey6 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey6EqualTo(String value) {
            addCriterion("TableKey6 =", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6NotEqualTo(String value) {
            addCriterion("TableKey6 <>", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6GreaterThan(String value) {
            addCriterion("TableKey6 >", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey6 >=", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6LessThan(String value) {
            addCriterion("TableKey6 <", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6LessThanOrEqualTo(String value) {
            addCriterion("TableKey6 <=", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6Like(String value) {
            addCriterion("TableKey6 like", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6NotLike(String value) {
            addCriterion("TableKey6 not like", value, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6In(List<String> values) {
            addCriterion("TableKey6 in", values, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6NotIn(List<String> values) {
            addCriterion("TableKey6 not in", values, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6Between(String value1, String value2) {
            addCriterion("TableKey6 between", value1, value2, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey6NotBetween(String value1, String value2) {
            addCriterion("TableKey6 not between", value1, value2, "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey7IsNull() {
            addCriterion("TableKey7 is null");
            return (Criteria) this;
        }

        public Criteria andTablekey7IsNotNull() {
            addCriterion("TableKey7 is not null");
            return (Criteria) this;
        }

        public Criteria andTablekey7EqualTo(String value) {
            addCriterion("TableKey7 =", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7NotEqualTo(String value) {
            addCriterion("TableKey7 <>", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7GreaterThan(String value) {
            addCriterion("TableKey7 >", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7GreaterThanOrEqualTo(String value) {
            addCriterion("TableKey7 >=", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7LessThan(String value) {
            addCriterion("TableKey7 <", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7LessThanOrEqualTo(String value) {
            addCriterion("TableKey7 <=", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7Like(String value) {
            addCriterion("TableKey7 like", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7NotLike(String value) {
            addCriterion("TableKey7 not like", value, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7In(List<String> values) {
            addCriterion("TableKey7 in", values, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7NotIn(List<String> values) {
            addCriterion("TableKey7 not in", values, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7Between(String value1, String value2) {
            addCriterion("TableKey7 between", value1, value2, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andTablekey7NotBetween(String value1, String value2) {
            addCriterion("TableKey7 not between", value1, value2, "tablekey7");
            return (Criteria) this;
        }

        public Criteria andLogcolumnIsNull() {
            addCriterion("LogColumn is null");
            return (Criteria) this;
        }

        public Criteria andLogcolumnIsNotNull() {
            addCriterion("LogColumn is not null");
            return (Criteria) this;
        }

        public Criteria andLogcolumnEqualTo(String value) {
            addCriterion("LogColumn =", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnNotEqualTo(String value) {
            addCriterion("LogColumn <>", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnGreaterThan(String value) {
            addCriterion("LogColumn >", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnGreaterThanOrEqualTo(String value) {
            addCriterion("LogColumn >=", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnLessThan(String value) {
            addCriterion("LogColumn <", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnLessThanOrEqualTo(String value) {
            addCriterion("LogColumn <=", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnLike(String value) {
            addCriterion("LogColumn like", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnNotLike(String value) {
            addCriterion("LogColumn not like", value, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnIn(List<String> values) {
            addCriterion("LogColumn in", values, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnNotIn(List<String> values) {
            addCriterion("LogColumn not in", values, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnBetween(String value1, String value2) {
            addCriterion("LogColumn between", value1, value2, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogcolumnNotBetween(String value1, String value2) {
            addCriterion("LogColumn not between", value1, value2, "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogactionIsNull() {
            addCriterion("LogAction is null");
            return (Criteria) this;
        }

        public Criteria andLogactionIsNotNull() {
            addCriterion("LogAction is not null");
            return (Criteria) this;
        }

        public Criteria andLogactionEqualTo(String value) {
            addCriterion("LogAction =", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionNotEqualTo(String value) {
            addCriterion("LogAction <>", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionGreaterThan(String value) {
            addCriterion("LogAction >", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionGreaterThanOrEqualTo(String value) {
            addCriterion("LogAction >=", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionLessThan(String value) {
            addCriterion("LogAction <", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionLessThanOrEqualTo(String value) {
            addCriterion("LogAction <=", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionLike(String value) {
            addCriterion("LogAction like", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionNotLike(String value) {
            addCriterion("LogAction not like", value, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionIn(List<String> values) {
            addCriterion("LogAction in", values, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionNotIn(List<String> values) {
            addCriterion("LogAction not in", values, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionBetween(String value1, String value2) {
            addCriterion("LogAction between", value1, value2, "logaction");
            return (Criteria) this;
        }

        public Criteria andLogactionNotBetween(String value1, String value2) {
            addCriterion("LogAction not between", value1, value2, "logaction");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionIsNull() {
            addCriterion("FieldDescription is null");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionIsNotNull() {
            addCriterion("FieldDescription is not null");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionEqualTo(String value) {
            addCriterion("FieldDescription =", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionNotEqualTo(String value) {
            addCriterion("FieldDescription <>", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionGreaterThan(String value) {
            addCriterion("FieldDescription >", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("FieldDescription >=", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionLessThan(String value) {
            addCriterion("FieldDescription <", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionLessThanOrEqualTo(String value) {
            addCriterion("FieldDescription <=", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionLike(String value) {
            addCriterion("FieldDescription like", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionNotLike(String value) {
            addCriterion("FieldDescription not like", value, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionIn(List<String> values) {
            addCriterion("FieldDescription in", values, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionNotIn(List<String> values) {
            addCriterion("FieldDescription not in", values, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionBetween(String value1, String value2) {
            addCriterion("FieldDescription between", value1, value2, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionNotBetween(String value1, String value2) {
            addCriterion("FieldDescription not between", value1, value2, "fielddescription");
            return (Criteria) this;
        }

        public Criteria andBeforevalueIsNull() {
            addCriterion("BeforeValue is null");
            return (Criteria) this;
        }

        public Criteria andBeforevalueIsNotNull() {
            addCriterion("BeforeValue is not null");
            return (Criteria) this;
        }

        public Criteria andBeforevalueEqualTo(String value) {
            addCriterion("BeforeValue =", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueNotEqualTo(String value) {
            addCriterion("BeforeValue <>", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueGreaterThan(String value) {
            addCriterion("BeforeValue >", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueGreaterThanOrEqualTo(String value) {
            addCriterion("BeforeValue >=", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueLessThan(String value) {
            addCriterion("BeforeValue <", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueLessThanOrEqualTo(String value) {
            addCriterion("BeforeValue <=", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueLike(String value) {
            addCriterion("BeforeValue like", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueNotLike(String value) {
            addCriterion("BeforeValue not like", value, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueIn(List<String> values) {
            addCriterion("BeforeValue in", values, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueNotIn(List<String> values) {
            addCriterion("BeforeValue not in", values, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueBetween(String value1, String value2) {
            addCriterion("BeforeValue between", value1, value2, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andBeforevalueNotBetween(String value1, String value2) {
            addCriterion("BeforeValue not between", value1, value2, "beforevalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueIsNull() {
            addCriterion("AfterValue is null");
            return (Criteria) this;
        }

        public Criteria andAftervalueIsNotNull() {
            addCriterion("AfterValue is not null");
            return (Criteria) this;
        }

        public Criteria andAftervalueEqualTo(String value) {
            addCriterion("AfterValue =", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueNotEqualTo(String value) {
            addCriterion("AfterValue <>", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueGreaterThan(String value) {
            addCriterion("AfterValue >", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueGreaterThanOrEqualTo(String value) {
            addCriterion("AfterValue >=", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueLessThan(String value) {
            addCriterion("AfterValue <", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueLessThanOrEqualTo(String value) {
            addCriterion("AfterValue <=", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueLike(String value) {
            addCriterion("AfterValue like", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueNotLike(String value) {
            addCriterion("AfterValue not like", value, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueIn(List<String> values) {
            addCriterion("AfterValue in", values, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueNotIn(List<String> values) {
            addCriterion("AfterValue not in", values, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueBetween(String value1, String value2) {
            addCriterion("AfterValue between", value1, value2, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueNotBetween(String value1, String value2) {
            addCriterion("AfterValue not between", value1, value2, "aftervalue");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeIsNull() {
            addCriterion("LogDateTime is null");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeIsNotNull() {
            addCriterion("LogDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeEqualTo(Date value) {
            addCriterion("LogDateTime =", value, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeNotEqualTo(Date value) {
            addCriterion("LogDateTime <>", value, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeGreaterThan(Date value) {
            addCriterion("LogDateTime >", value, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LogDateTime >=", value, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeLessThan(Date value) {
            addCriterion("LogDateTime <", value, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("LogDateTime <=", value, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeIn(List<Date> values) {
            addCriterion("LogDateTime in", values, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeNotIn(List<Date> values) {
            addCriterion("LogDateTime not in", values, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeBetween(Date value1, Date value2) {
            addCriterion("LogDateTime between", value1, value2, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLogdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("LogDateTime not between", value1, value2, "logdatetime");
            return (Criteria) this;
        }

        public Criteria andLoghostnameIsNull() {
            addCriterion("LogHostName is null");
            return (Criteria) this;
        }

        public Criteria andLoghostnameIsNotNull() {
            addCriterion("LogHostName is not null");
            return (Criteria) this;
        }

        public Criteria andLoghostnameEqualTo(String value) {
            addCriterion("LogHostName =", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameNotEqualTo(String value) {
            addCriterion("LogHostName <>", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameGreaterThan(String value) {
            addCriterion("LogHostName >", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameGreaterThanOrEqualTo(String value) {
            addCriterion("LogHostName >=", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameLessThan(String value) {
            addCriterion("LogHostName <", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameLessThanOrEqualTo(String value) {
            addCriterion("LogHostName <=", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameLike(String value) {
            addCriterion("LogHostName like", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameNotLike(String value) {
            addCriterion("LogHostName not like", value, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameIn(List<String> values) {
            addCriterion("LogHostName in", values, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameNotIn(List<String> values) {
            addCriterion("LogHostName not in", values, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameBetween(String value1, String value2) {
            addCriterion("LogHostName between", value1, value2, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLoghostnameNotBetween(String value1, String value2) {
            addCriterion("LogHostName not between", value1, value2, "loghostname");
            return (Criteria) this;
        }

        public Criteria andLogusernameIsNull() {
            addCriterion("LogUserName is null");
            return (Criteria) this;
        }

        public Criteria andLogusernameIsNotNull() {
            addCriterion("LogUserName is not null");
            return (Criteria) this;
        }

        public Criteria andLogusernameEqualTo(String value) {
            addCriterion("LogUserName =", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameNotEqualTo(String value) {
            addCriterion("LogUserName <>", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameGreaterThan(String value) {
            addCriterion("LogUserName >", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameGreaterThanOrEqualTo(String value) {
            addCriterion("LogUserName >=", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameLessThan(String value) {
            addCriterion("LogUserName <", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameLessThanOrEqualTo(String value) {
            addCriterion("LogUserName <=", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameLike(String value) {
            addCriterion("LogUserName like", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameNotLike(String value) {
            addCriterion("LogUserName not like", value, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameIn(List<String> values) {
            addCriterion("LogUserName in", values, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameNotIn(List<String> values) {
            addCriterion("LogUserName not in", values, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameBetween(String value1, String value2) {
            addCriterion("LogUserName between", value1, value2, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogusernameNotBetween(String value1, String value2) {
            addCriterion("LogUserName not between", value1, value2, "logusername");
            return (Criteria) this;
        }

        public Criteria andLogtableLikeInsensitive(String value) {
            addCriterion("upper(LogTable) like", value.toUpperCase(), "logtable");
            return (Criteria) this;
        }

        public Criteria andTablekey1LikeInsensitive(String value) {
            addCriterion("upper(TableKey1) like", value.toUpperCase(), "tablekey1");
            return (Criteria) this;
        }

        public Criteria andTablekey2LikeInsensitive(String value) {
            addCriterion("upper(TableKey2) like", value.toUpperCase(), "tablekey2");
            return (Criteria) this;
        }

        public Criteria andTablekey3LikeInsensitive(String value) {
            addCriterion("upper(TableKey3) like", value.toUpperCase(), "tablekey3");
            return (Criteria) this;
        }

        public Criteria andTablekey4LikeInsensitive(String value) {
            addCriterion("upper(TableKey4) like", value.toUpperCase(), "tablekey4");
            return (Criteria) this;
        }

        public Criteria andTablekey5LikeInsensitive(String value) {
            addCriterion("upper(TableKey5) like", value.toUpperCase(), "tablekey5");
            return (Criteria) this;
        }

        public Criteria andTablekey6LikeInsensitive(String value) {
            addCriterion("upper(TableKey6) like", value.toUpperCase(), "tablekey6");
            return (Criteria) this;
        }

        public Criteria andTablekey7LikeInsensitive(String value) {
            addCriterion("upper(TableKey7) like", value.toUpperCase(), "tablekey7");
            return (Criteria) this;
        }

        public Criteria andLogcolumnLikeInsensitive(String value) {
            addCriterion("upper(LogColumn) like", value.toUpperCase(), "logcolumn");
            return (Criteria) this;
        }

        public Criteria andLogactionLikeInsensitive(String value) {
            addCriterion("upper(LogAction) like", value.toUpperCase(), "logaction");
            return (Criteria) this;
        }

        public Criteria andFielddescriptionLikeInsensitive(String value) {
            addCriterion("upper(FieldDescription) like", value.toUpperCase(), "fielddescription");
            return (Criteria) this;
        }

        public Criteria andBeforevalueLikeInsensitive(String value) {
            addCriterion("upper(BeforeValue) like", value.toUpperCase(), "beforevalue");
            return (Criteria) this;
        }

        public Criteria andAftervalueLikeInsensitive(String value) {
            addCriterion("upper(AfterValue) like", value.toUpperCase(), "aftervalue");
            return (Criteria) this;
        }

        public Criteria andLoghostnameLikeInsensitive(String value) {
            addCriterion("upper(LogHostName) like", value.toUpperCase(), "loghostname");
            return (Criteria) this;
        }

        public Criteria andLogusernameLikeInsensitive(String value) {
            addCriterion("upper(LogUserName) like", value.toUpperCase(), "logusername");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GenericLog
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GenericLog
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}