package com.example.migration.dao.master.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table InstrumentVersion
 */
public class InstrumentVersion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Instrument
     *
     * @mbg.generated
     */
    private String instrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Market
     *
     * @mbg.generated
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ShortName
     *
     * @mbg.generated
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.CName
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.CShortName
     *
     * @mbg.generated
     */
    private String cshortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.InstrumentClass
     *
     * @mbg.generated
     */
    private String instrumentclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ProdCode
     *
     * @mbg.generated
     */
    private String prodcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.LotSize
     *
     * @mbg.generated
     */
    private BigDecimal lotsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.TransactionValueLimit
     *
     * @mbg.generated
     */
    private BigDecimal transactionvaluelimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.TransactionQtyLimit
     *
     * @mbg.generated
     */
    private BigDecimal transactionqtylimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.DailyValueLimit
     *
     * @mbg.generated
     */
    private BigDecimal dailyvaluelimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.DailyQtyLimit
     *
     * @mbg.generated
     */
    private BigDecimal dailyqtylimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ExpiryDate
     *
     * @mbg.generated
     */
    private Date expirydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Active
     *
     * @mbg.generated
     */
    private String active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.MarginPercent
     *
     * @mbg.generated
     */
    private BigDecimal marginpercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Series
     *
     * @mbg.generated
     */
    private String series;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.PriceCap
     *
     * @mbg.generated
     */
    private BigDecimal pricecap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.CalculationPrice
     *
     * @mbg.generated
     */
    private BigDecimal calculationprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Suspended
     *
     * @mbg.generated
     */
    private String suspended;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.TradingCCY
     *
     * @mbg.generated
     */
    private String tradingccy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ExchangeCode
     *
     * @mbg.generated
     */
    private String exchangecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ExchangeInternalCode
     *
     * @mbg.generated
     */
    private String exchangeinternalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Bloomberg
     *
     * @mbg.generated
     */
    private String bloomberg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Reuter
     *
     * @mbg.generated
     */
    private String reuter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ISIN
     *
     * @mbg.generated
     */
    private String isin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Sedol
     *
     * @mbg.generated
     */
    private String sedol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.FirstDealingDate
     *
     * @mbg.generated
     */
    private Date firstdealingdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.LastDealingDate
     *
     * @mbg.generated
     */
    private Date lastdealingdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ElectronicClearing
     *
     * @mbg.generated
     */
    private String electronicclearing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ShortSell
     *
     * @mbg.generated
     */
    private String shortsell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.ParValue
     *
     * @mbg.generated
     */
    private BigDecimal parvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee1
     *
     * @mbg.generated
     */
    private String fee1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee2
     *
     * @mbg.generated
     */
    private String fee2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee3
     *
     * @mbg.generated
     */
    private String fee3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee4
     *
     * @mbg.generated
     */
    private String fee4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee5
     *
     * @mbg.generated
     */
    private String fee5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee6
     *
     * @mbg.generated
     */
    private String fee6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee7
     *
     * @mbg.generated
     */
    private String fee7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee8
     *
     * @mbg.generated
     */
    private String fee8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee9
     *
     * @mbg.generated
     */
    private String fee9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Fee10
     *
     * @mbg.generated
     */
    private String fee10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.SpreadTableCode
     *
     * @mbg.generated
     */
    private String spreadtablecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.StatusFlag
     *
     * @mbg.generated
     */
    private String statusflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.InstrumentType
     *
     * @mbg.generated
     */
    private String instrumenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.DateOfListed
     *
     * @mbg.generated
     */
    private Date dateoflisted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.IlliquidCollateralCalculation
     *
     * @mbg.generated
     */
    private String illiquidcollateralcalculation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.SyncRef
     *
     * @mbg.generated
     */
    private String syncref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.UnderMarket
     *
     * @mbg.generated
     */
    private String undermarket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.UnderStock
     *
     * @mbg.generated
     */
    private String understock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.SuspendFrom
     *
     * @mbg.generated
     */
    private Date suspendfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.LastSuspendPrice
     *
     * @mbg.generated
     */
    private BigDecimal lastsuspendprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.InstDepotCode
     *
     * @mbg.generated
     */
    private String instdepotcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.InstLocation
     *
     * @mbg.generated
     */
    private String instlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.NAVDate
     *
     * @mbg.generated
     */
    private Date navdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.CollateralRatio
     *
     * @mbg.generated
     */
    private BigDecimal collateralratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.InterestRateCategory
     *
     * @mbg.generated
     */
    private String interestratecategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.NoBuy
     *
     * @mbg.generated
     */
    private String nobuy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.NoSell
     *
     * @mbg.generated
     */
    private String nosell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.SellOnlyByCSC
     *
     * @mbg.generated
     */
    private String sellonlybycsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.GlobalInstrumentType
     *
     * @mbg.generated
     */
    private String globalinstrumenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.IDCInstrumentType
     *
     * @mbg.generated
     */
    private String idcinstrumenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.Tier
     *
     * @mbg.generated
     */
    private String tier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.LogDateTime
     *
     * @mbg.generated
     */
    private Date logdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.LogHostName
     *
     * @mbg.generated
     */
    private String loghostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentVersion.LogUserName
     *
     * @mbg.generated
     */
    private String logusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Date
     *
     * @return the value of InstrumentVersion.Date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Date
     *
     * @param date the value for InstrumentVersion.Date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Instrument
     *
     * @return the value of InstrumentVersion.Instrument
     *
     * @mbg.generated
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Instrument
     *
     * @param instrument the value for InstrumentVersion.Instrument
     *
     * @mbg.generated
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument == null ? null : instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Market
     *
     * @return the value of InstrumentVersion.Market
     *
     * @mbg.generated
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Market
     *
     * @param market the value for InstrumentVersion.Market
     *
     * @mbg.generated
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Name
     *
     * @return the value of InstrumentVersion.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Name
     *
     * @param name the value for InstrumentVersion.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ShortName
     *
     * @return the value of InstrumentVersion.ShortName
     *
     * @mbg.generated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ShortName
     *
     * @param shortname the value for InstrumentVersion.ShortName
     *
     * @mbg.generated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.CName
     *
     * @return the value of InstrumentVersion.CName
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.CName
     *
     * @param cname the value for InstrumentVersion.CName
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.CShortName
     *
     * @return the value of InstrumentVersion.CShortName
     *
     * @mbg.generated
     */
    public String getCshortname() {
        return cshortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.CShortName
     *
     * @param cshortname the value for InstrumentVersion.CShortName
     *
     * @mbg.generated
     */
    public void setCshortname(String cshortname) {
        this.cshortname = cshortname == null ? null : cshortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.InstrumentClass
     *
     * @return the value of InstrumentVersion.InstrumentClass
     *
     * @mbg.generated
     */
    public String getInstrumentclass() {
        return instrumentclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.InstrumentClass
     *
     * @param instrumentclass the value for InstrumentVersion.InstrumentClass
     *
     * @mbg.generated
     */
    public void setInstrumentclass(String instrumentclass) {
        this.instrumentclass = instrumentclass == null ? null : instrumentclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ProdCode
     *
     * @return the value of InstrumentVersion.ProdCode
     *
     * @mbg.generated
     */
    public String getProdcode() {
        return prodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ProdCode
     *
     * @param prodcode the value for InstrumentVersion.ProdCode
     *
     * @mbg.generated
     */
    public void setProdcode(String prodcode) {
        this.prodcode = prodcode == null ? null : prodcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.LotSize
     *
     * @return the value of InstrumentVersion.LotSize
     *
     * @mbg.generated
     */
    public BigDecimal getLotsize() {
        return lotsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.LotSize
     *
     * @param lotsize the value for InstrumentVersion.LotSize
     *
     * @mbg.generated
     */
    public void setLotsize(BigDecimal lotsize) {
        this.lotsize = lotsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Price
     *
     * @return the value of InstrumentVersion.Price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Price
     *
     * @param price the value for InstrumentVersion.Price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.TransactionValueLimit
     *
     * @return the value of InstrumentVersion.TransactionValueLimit
     *
     * @mbg.generated
     */
    public BigDecimal getTransactionvaluelimit() {
        return transactionvaluelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.TransactionValueLimit
     *
     * @param transactionvaluelimit the value for InstrumentVersion.TransactionValueLimit
     *
     * @mbg.generated
     */
    public void setTransactionvaluelimit(BigDecimal transactionvaluelimit) {
        this.transactionvaluelimit = transactionvaluelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.TransactionQtyLimit
     *
     * @return the value of InstrumentVersion.TransactionQtyLimit
     *
     * @mbg.generated
     */
    public BigDecimal getTransactionqtylimit() {
        return transactionqtylimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.TransactionQtyLimit
     *
     * @param transactionqtylimit the value for InstrumentVersion.TransactionQtyLimit
     *
     * @mbg.generated
     */
    public void setTransactionqtylimit(BigDecimal transactionqtylimit) {
        this.transactionqtylimit = transactionqtylimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.DailyValueLimit
     *
     * @return the value of InstrumentVersion.DailyValueLimit
     *
     * @mbg.generated
     */
    public BigDecimal getDailyvaluelimit() {
        return dailyvaluelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.DailyValueLimit
     *
     * @param dailyvaluelimit the value for InstrumentVersion.DailyValueLimit
     *
     * @mbg.generated
     */
    public void setDailyvaluelimit(BigDecimal dailyvaluelimit) {
        this.dailyvaluelimit = dailyvaluelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.DailyQtyLimit
     *
     * @return the value of InstrumentVersion.DailyQtyLimit
     *
     * @mbg.generated
     */
    public BigDecimal getDailyqtylimit() {
        return dailyqtylimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.DailyQtyLimit
     *
     * @param dailyqtylimit the value for InstrumentVersion.DailyQtyLimit
     *
     * @mbg.generated
     */
    public void setDailyqtylimit(BigDecimal dailyqtylimit) {
        this.dailyqtylimit = dailyqtylimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ExpiryDate
     *
     * @return the value of InstrumentVersion.ExpiryDate
     *
     * @mbg.generated
     */
    public Date getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ExpiryDate
     *
     * @param expirydate the value for InstrumentVersion.ExpiryDate
     *
     * @mbg.generated
     */
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Active
     *
     * @return the value of InstrumentVersion.Active
     *
     * @mbg.generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Active
     *
     * @param active the value for InstrumentVersion.Active
     *
     * @mbg.generated
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.MarginPercent
     *
     * @return the value of InstrumentVersion.MarginPercent
     *
     * @mbg.generated
     */
    public BigDecimal getMarginpercent() {
        return marginpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.MarginPercent
     *
     * @param marginpercent the value for InstrumentVersion.MarginPercent
     *
     * @mbg.generated
     */
    public void setMarginpercent(BigDecimal marginpercent) {
        this.marginpercent = marginpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Series
     *
     * @return the value of InstrumentVersion.Series
     *
     * @mbg.generated
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Series
     *
     * @param series the value for InstrumentVersion.Series
     *
     * @mbg.generated
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.PriceCap
     *
     * @return the value of InstrumentVersion.PriceCap
     *
     * @mbg.generated
     */
    public BigDecimal getPricecap() {
        return pricecap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.PriceCap
     *
     * @param pricecap the value for InstrumentVersion.PriceCap
     *
     * @mbg.generated
     */
    public void setPricecap(BigDecimal pricecap) {
        this.pricecap = pricecap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.CalculationPrice
     *
     * @return the value of InstrumentVersion.CalculationPrice
     *
     * @mbg.generated
     */
    public BigDecimal getCalculationprice() {
        return calculationprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.CalculationPrice
     *
     * @param calculationprice the value for InstrumentVersion.CalculationPrice
     *
     * @mbg.generated
     */
    public void setCalculationprice(BigDecimal calculationprice) {
        this.calculationprice = calculationprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Suspended
     *
     * @return the value of InstrumentVersion.Suspended
     *
     * @mbg.generated
     */
    public String getSuspended() {
        return suspended;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Suspended
     *
     * @param suspended the value for InstrumentVersion.Suspended
     *
     * @mbg.generated
     */
    public void setSuspended(String suspended) {
        this.suspended = suspended == null ? null : suspended.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.TradingCCY
     *
     * @return the value of InstrumentVersion.TradingCCY
     *
     * @mbg.generated
     */
    public String getTradingccy() {
        return tradingccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.TradingCCY
     *
     * @param tradingccy the value for InstrumentVersion.TradingCCY
     *
     * @mbg.generated
     */
    public void setTradingccy(String tradingccy) {
        this.tradingccy = tradingccy == null ? null : tradingccy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ExchangeCode
     *
     * @return the value of InstrumentVersion.ExchangeCode
     *
     * @mbg.generated
     */
    public String getExchangecode() {
        return exchangecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ExchangeCode
     *
     * @param exchangecode the value for InstrumentVersion.ExchangeCode
     *
     * @mbg.generated
     */
    public void setExchangecode(String exchangecode) {
        this.exchangecode = exchangecode == null ? null : exchangecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ExchangeInternalCode
     *
     * @return the value of InstrumentVersion.ExchangeInternalCode
     *
     * @mbg.generated
     */
    public String getExchangeinternalcode() {
        return exchangeinternalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ExchangeInternalCode
     *
     * @param exchangeinternalcode the value for InstrumentVersion.ExchangeInternalCode
     *
     * @mbg.generated
     */
    public void setExchangeinternalcode(String exchangeinternalcode) {
        this.exchangeinternalcode = exchangeinternalcode == null ? null : exchangeinternalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Bloomberg
     *
     * @return the value of InstrumentVersion.Bloomberg
     *
     * @mbg.generated
     */
    public String getBloomberg() {
        return bloomberg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Bloomberg
     *
     * @param bloomberg the value for InstrumentVersion.Bloomberg
     *
     * @mbg.generated
     */
    public void setBloomberg(String bloomberg) {
        this.bloomberg = bloomberg == null ? null : bloomberg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Reuter
     *
     * @return the value of InstrumentVersion.Reuter
     *
     * @mbg.generated
     */
    public String getReuter() {
        return reuter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Reuter
     *
     * @param reuter the value for InstrumentVersion.Reuter
     *
     * @mbg.generated
     */
    public void setReuter(String reuter) {
        this.reuter = reuter == null ? null : reuter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ISIN
     *
     * @return the value of InstrumentVersion.ISIN
     *
     * @mbg.generated
     */
    public String getIsin() {
        return isin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ISIN
     *
     * @param isin the value for InstrumentVersion.ISIN
     *
     * @mbg.generated
     */
    public void setIsin(String isin) {
        this.isin = isin == null ? null : isin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Sedol
     *
     * @return the value of InstrumentVersion.Sedol
     *
     * @mbg.generated
     */
    public String getSedol() {
        return sedol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Sedol
     *
     * @param sedol the value for InstrumentVersion.Sedol
     *
     * @mbg.generated
     */
    public void setSedol(String sedol) {
        this.sedol = sedol == null ? null : sedol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.FirstDealingDate
     *
     * @return the value of InstrumentVersion.FirstDealingDate
     *
     * @mbg.generated
     */
    public Date getFirstdealingdate() {
        return firstdealingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.FirstDealingDate
     *
     * @param firstdealingdate the value for InstrumentVersion.FirstDealingDate
     *
     * @mbg.generated
     */
    public void setFirstdealingdate(Date firstdealingdate) {
        this.firstdealingdate = firstdealingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.LastDealingDate
     *
     * @return the value of InstrumentVersion.LastDealingDate
     *
     * @mbg.generated
     */
    public Date getLastdealingdate() {
        return lastdealingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.LastDealingDate
     *
     * @param lastdealingdate the value for InstrumentVersion.LastDealingDate
     *
     * @mbg.generated
     */
    public void setLastdealingdate(Date lastdealingdate) {
        this.lastdealingdate = lastdealingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ElectronicClearing
     *
     * @return the value of InstrumentVersion.ElectronicClearing
     *
     * @mbg.generated
     */
    public String getElectronicclearing() {
        return electronicclearing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ElectronicClearing
     *
     * @param electronicclearing the value for InstrumentVersion.ElectronicClearing
     *
     * @mbg.generated
     */
    public void setElectronicclearing(String electronicclearing) {
        this.electronicclearing = electronicclearing == null ? null : electronicclearing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ShortSell
     *
     * @return the value of InstrumentVersion.ShortSell
     *
     * @mbg.generated
     */
    public String getShortsell() {
        return shortsell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ShortSell
     *
     * @param shortsell the value for InstrumentVersion.ShortSell
     *
     * @mbg.generated
     */
    public void setShortsell(String shortsell) {
        this.shortsell = shortsell == null ? null : shortsell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.ParValue
     *
     * @return the value of InstrumentVersion.ParValue
     *
     * @mbg.generated
     */
    public BigDecimal getParvalue() {
        return parvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.ParValue
     *
     * @param parvalue the value for InstrumentVersion.ParValue
     *
     * @mbg.generated
     */
    public void setParvalue(BigDecimal parvalue) {
        this.parvalue = parvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee1
     *
     * @return the value of InstrumentVersion.Fee1
     *
     * @mbg.generated
     */
    public String getFee1() {
        return fee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee1
     *
     * @param fee1 the value for InstrumentVersion.Fee1
     *
     * @mbg.generated
     */
    public void setFee1(String fee1) {
        this.fee1 = fee1 == null ? null : fee1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee2
     *
     * @return the value of InstrumentVersion.Fee2
     *
     * @mbg.generated
     */
    public String getFee2() {
        return fee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee2
     *
     * @param fee2 the value for InstrumentVersion.Fee2
     *
     * @mbg.generated
     */
    public void setFee2(String fee2) {
        this.fee2 = fee2 == null ? null : fee2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee3
     *
     * @return the value of InstrumentVersion.Fee3
     *
     * @mbg.generated
     */
    public String getFee3() {
        return fee3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee3
     *
     * @param fee3 the value for InstrumentVersion.Fee3
     *
     * @mbg.generated
     */
    public void setFee3(String fee3) {
        this.fee3 = fee3 == null ? null : fee3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee4
     *
     * @return the value of InstrumentVersion.Fee4
     *
     * @mbg.generated
     */
    public String getFee4() {
        return fee4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee4
     *
     * @param fee4 the value for InstrumentVersion.Fee4
     *
     * @mbg.generated
     */
    public void setFee4(String fee4) {
        this.fee4 = fee4 == null ? null : fee4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee5
     *
     * @return the value of InstrumentVersion.Fee5
     *
     * @mbg.generated
     */
    public String getFee5() {
        return fee5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee5
     *
     * @param fee5 the value for InstrumentVersion.Fee5
     *
     * @mbg.generated
     */
    public void setFee5(String fee5) {
        this.fee5 = fee5 == null ? null : fee5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee6
     *
     * @return the value of InstrumentVersion.Fee6
     *
     * @mbg.generated
     */
    public String getFee6() {
        return fee6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee6
     *
     * @param fee6 the value for InstrumentVersion.Fee6
     *
     * @mbg.generated
     */
    public void setFee6(String fee6) {
        this.fee6 = fee6 == null ? null : fee6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee7
     *
     * @return the value of InstrumentVersion.Fee7
     *
     * @mbg.generated
     */
    public String getFee7() {
        return fee7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee7
     *
     * @param fee7 the value for InstrumentVersion.Fee7
     *
     * @mbg.generated
     */
    public void setFee7(String fee7) {
        this.fee7 = fee7 == null ? null : fee7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee8
     *
     * @return the value of InstrumentVersion.Fee8
     *
     * @mbg.generated
     */
    public String getFee8() {
        return fee8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee8
     *
     * @param fee8 the value for InstrumentVersion.Fee8
     *
     * @mbg.generated
     */
    public void setFee8(String fee8) {
        this.fee8 = fee8 == null ? null : fee8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee9
     *
     * @return the value of InstrumentVersion.Fee9
     *
     * @mbg.generated
     */
    public String getFee9() {
        return fee9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee9
     *
     * @param fee9 the value for InstrumentVersion.Fee9
     *
     * @mbg.generated
     */
    public void setFee9(String fee9) {
        this.fee9 = fee9 == null ? null : fee9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Fee10
     *
     * @return the value of InstrumentVersion.Fee10
     *
     * @mbg.generated
     */
    public String getFee10() {
        return fee10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Fee10
     *
     * @param fee10 the value for InstrumentVersion.Fee10
     *
     * @mbg.generated
     */
    public void setFee10(String fee10) {
        this.fee10 = fee10 == null ? null : fee10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Category
     *
     * @return the value of InstrumentVersion.Category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Category
     *
     * @param category the value for InstrumentVersion.Category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.SpreadTableCode
     *
     * @return the value of InstrumentVersion.SpreadTableCode
     *
     * @mbg.generated
     */
    public String getSpreadtablecode() {
        return spreadtablecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.SpreadTableCode
     *
     * @param spreadtablecode the value for InstrumentVersion.SpreadTableCode
     *
     * @mbg.generated
     */
    public void setSpreadtablecode(String spreadtablecode) {
        this.spreadtablecode = spreadtablecode == null ? null : spreadtablecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.StatusFlag
     *
     * @return the value of InstrumentVersion.StatusFlag
     *
     * @mbg.generated
     */
    public String getStatusflag() {
        return statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.StatusFlag
     *
     * @param statusflag the value for InstrumentVersion.StatusFlag
     *
     * @mbg.generated
     */
    public void setStatusflag(String statusflag) {
        this.statusflag = statusflag == null ? null : statusflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.InstrumentType
     *
     * @return the value of InstrumentVersion.InstrumentType
     *
     * @mbg.generated
     */
    public String getInstrumenttype() {
        return instrumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.InstrumentType
     *
     * @param instrumenttype the value for InstrumentVersion.InstrumentType
     *
     * @mbg.generated
     */
    public void setInstrumenttype(String instrumenttype) {
        this.instrumenttype = instrumenttype == null ? null : instrumenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.DateOfListed
     *
     * @return the value of InstrumentVersion.DateOfListed
     *
     * @mbg.generated
     */
    public Date getDateoflisted() {
        return dateoflisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.DateOfListed
     *
     * @param dateoflisted the value for InstrumentVersion.DateOfListed
     *
     * @mbg.generated
     */
    public void setDateoflisted(Date dateoflisted) {
        this.dateoflisted = dateoflisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.IlliquidCollateralCalculation
     *
     * @return the value of InstrumentVersion.IlliquidCollateralCalculation
     *
     * @mbg.generated
     */
    public String getIlliquidcollateralcalculation() {
        return illiquidcollateralcalculation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.IlliquidCollateralCalculation
     *
     * @param illiquidcollateralcalculation the value for InstrumentVersion.IlliquidCollateralCalculation
     *
     * @mbg.generated
     */
    public void setIlliquidcollateralcalculation(String illiquidcollateralcalculation) {
        this.illiquidcollateralcalculation = illiquidcollateralcalculation == null ? null : illiquidcollateralcalculation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.SyncRef
     *
     * @return the value of InstrumentVersion.SyncRef
     *
     * @mbg.generated
     */
    public String getSyncref() {
        return syncref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.SyncRef
     *
     * @param syncref the value for InstrumentVersion.SyncRef
     *
     * @mbg.generated
     */
    public void setSyncref(String syncref) {
        this.syncref = syncref == null ? null : syncref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.UnderMarket
     *
     * @return the value of InstrumentVersion.UnderMarket
     *
     * @mbg.generated
     */
    public String getUndermarket() {
        return undermarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.UnderMarket
     *
     * @param undermarket the value for InstrumentVersion.UnderMarket
     *
     * @mbg.generated
     */
    public void setUndermarket(String undermarket) {
        this.undermarket = undermarket == null ? null : undermarket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.UnderStock
     *
     * @return the value of InstrumentVersion.UnderStock
     *
     * @mbg.generated
     */
    public String getUnderstock() {
        return understock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.UnderStock
     *
     * @param understock the value for InstrumentVersion.UnderStock
     *
     * @mbg.generated
     */
    public void setUnderstock(String understock) {
        this.understock = understock == null ? null : understock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.SuspendFrom
     *
     * @return the value of InstrumentVersion.SuspendFrom
     *
     * @mbg.generated
     */
    public Date getSuspendfrom() {
        return suspendfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.SuspendFrom
     *
     * @param suspendfrom the value for InstrumentVersion.SuspendFrom
     *
     * @mbg.generated
     */
    public void setSuspendfrom(Date suspendfrom) {
        this.suspendfrom = suspendfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.LastSuspendPrice
     *
     * @return the value of InstrumentVersion.LastSuspendPrice
     *
     * @mbg.generated
     */
    public BigDecimal getLastsuspendprice() {
        return lastsuspendprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.LastSuspendPrice
     *
     * @param lastsuspendprice the value for InstrumentVersion.LastSuspendPrice
     *
     * @mbg.generated
     */
    public void setLastsuspendprice(BigDecimal lastsuspendprice) {
        this.lastsuspendprice = lastsuspendprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.InstDepotCode
     *
     * @return the value of InstrumentVersion.InstDepotCode
     *
     * @mbg.generated
     */
    public String getInstdepotcode() {
        return instdepotcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.InstDepotCode
     *
     * @param instdepotcode the value for InstrumentVersion.InstDepotCode
     *
     * @mbg.generated
     */
    public void setInstdepotcode(String instdepotcode) {
        this.instdepotcode = instdepotcode == null ? null : instdepotcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.InstLocation
     *
     * @return the value of InstrumentVersion.InstLocation
     *
     * @mbg.generated
     */
    public String getInstlocation() {
        return instlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.InstLocation
     *
     * @param instlocation the value for InstrumentVersion.InstLocation
     *
     * @mbg.generated
     */
    public void setInstlocation(String instlocation) {
        this.instlocation = instlocation == null ? null : instlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.NAVDate
     *
     * @return the value of InstrumentVersion.NAVDate
     *
     * @mbg.generated
     */
    public Date getNavdate() {
        return navdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.NAVDate
     *
     * @param navdate the value for InstrumentVersion.NAVDate
     *
     * @mbg.generated
     */
    public void setNavdate(Date navdate) {
        this.navdate = navdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.CollateralRatio
     *
     * @return the value of InstrumentVersion.CollateralRatio
     *
     * @mbg.generated
     */
    public BigDecimal getCollateralratio() {
        return collateralratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.CollateralRatio
     *
     * @param collateralratio the value for InstrumentVersion.CollateralRatio
     *
     * @mbg.generated
     */
    public void setCollateralratio(BigDecimal collateralratio) {
        this.collateralratio = collateralratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.InterestRateCategory
     *
     * @return the value of InstrumentVersion.InterestRateCategory
     *
     * @mbg.generated
     */
    public String getInterestratecategory() {
        return interestratecategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.InterestRateCategory
     *
     * @param interestratecategory the value for InstrumentVersion.InterestRateCategory
     *
     * @mbg.generated
     */
    public void setInterestratecategory(String interestratecategory) {
        this.interestratecategory = interestratecategory == null ? null : interestratecategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.NoBuy
     *
     * @return the value of InstrumentVersion.NoBuy
     *
     * @mbg.generated
     */
    public String getNobuy() {
        return nobuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.NoBuy
     *
     * @param nobuy the value for InstrumentVersion.NoBuy
     *
     * @mbg.generated
     */
    public void setNobuy(String nobuy) {
        this.nobuy = nobuy == null ? null : nobuy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.NoSell
     *
     * @return the value of InstrumentVersion.NoSell
     *
     * @mbg.generated
     */
    public String getNosell() {
        return nosell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.NoSell
     *
     * @param nosell the value for InstrumentVersion.NoSell
     *
     * @mbg.generated
     */
    public void setNosell(String nosell) {
        this.nosell = nosell == null ? null : nosell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.SellOnlyByCSC
     *
     * @return the value of InstrumentVersion.SellOnlyByCSC
     *
     * @mbg.generated
     */
    public String getSellonlybycsc() {
        return sellonlybycsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.SellOnlyByCSC
     *
     * @param sellonlybycsc the value for InstrumentVersion.SellOnlyByCSC
     *
     * @mbg.generated
     */
    public void setSellonlybycsc(String sellonlybycsc) {
        this.sellonlybycsc = sellonlybycsc == null ? null : sellonlybycsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.GlobalInstrumentType
     *
     * @return the value of InstrumentVersion.GlobalInstrumentType
     *
     * @mbg.generated
     */
    public String getGlobalinstrumenttype() {
        return globalinstrumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.GlobalInstrumentType
     *
     * @param globalinstrumenttype the value for InstrumentVersion.GlobalInstrumentType
     *
     * @mbg.generated
     */
    public void setGlobalinstrumenttype(String globalinstrumenttype) {
        this.globalinstrumenttype = globalinstrumenttype == null ? null : globalinstrumenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.IDCInstrumentType
     *
     * @return the value of InstrumentVersion.IDCInstrumentType
     *
     * @mbg.generated
     */
    public String getIdcinstrumenttype() {
        return idcinstrumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.IDCInstrumentType
     *
     * @param idcinstrumenttype the value for InstrumentVersion.IDCInstrumentType
     *
     * @mbg.generated
     */
    public void setIdcinstrumenttype(String idcinstrumenttype) {
        this.idcinstrumenttype = idcinstrumenttype == null ? null : idcinstrumenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.Tier
     *
     * @return the value of InstrumentVersion.Tier
     *
     * @mbg.generated
     */
    public String getTier() {
        return tier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.Tier
     *
     * @param tier the value for InstrumentVersion.Tier
     *
     * @mbg.generated
     */
    public void setTier(String tier) {
        this.tier = tier == null ? null : tier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.LogDateTime
     *
     * @return the value of InstrumentVersion.LogDateTime
     *
     * @mbg.generated
     */
    public Date getLogdatetime() {
        return logdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.LogDateTime
     *
     * @param logdatetime the value for InstrumentVersion.LogDateTime
     *
     * @mbg.generated
     */
    public void setLogdatetime(Date logdatetime) {
        this.logdatetime = logdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.LogHostName
     *
     * @return the value of InstrumentVersion.LogHostName
     *
     * @mbg.generated
     */
    public String getLoghostname() {
        return loghostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.LogHostName
     *
     * @param loghostname the value for InstrumentVersion.LogHostName
     *
     * @mbg.generated
     */
    public void setLoghostname(String loghostname) {
        this.loghostname = loghostname == null ? null : loghostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentVersion.LogUserName
     *
     * @return the value of InstrumentVersion.LogUserName
     *
     * @mbg.generated
     */
    public String getLogusername() {
        return logusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentVersion.LogUserName
     *
     * @param logusername the value for InstrumentVersion.LogUserName
     *
     * @mbg.generated
     */
    public void setLogusername(String logusername) {
        this.logusername = logusername == null ? null : logusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InstrumentVersion other = (InstrumentVersion) that;
        return (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getInstrument() == null ? other.getInstrument() == null : this.getInstrument().equals(other.getInstrument()))
            && (this.getMarket() == null ? other.getMarket() == null : this.getMarket().equals(other.getMarket()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getShortname() == null ? other.getShortname() == null : this.getShortname().equals(other.getShortname()))
            && (this.getCname() == null ? other.getCname() == null : this.getCname().equals(other.getCname()))
            && (this.getCshortname() == null ? other.getCshortname() == null : this.getCshortname().equals(other.getCshortname()))
            && (this.getInstrumentclass() == null ? other.getInstrumentclass() == null : this.getInstrumentclass().equals(other.getInstrumentclass()))
            && (this.getProdcode() == null ? other.getProdcode() == null : this.getProdcode().equals(other.getProdcode()))
            && (this.getLotsize() == null ? other.getLotsize() == null : this.getLotsize().equals(other.getLotsize()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getTransactionvaluelimit() == null ? other.getTransactionvaluelimit() == null : this.getTransactionvaluelimit().equals(other.getTransactionvaluelimit()))
            && (this.getTransactionqtylimit() == null ? other.getTransactionqtylimit() == null : this.getTransactionqtylimit().equals(other.getTransactionqtylimit()))
            && (this.getDailyvaluelimit() == null ? other.getDailyvaluelimit() == null : this.getDailyvaluelimit().equals(other.getDailyvaluelimit()))
            && (this.getDailyqtylimit() == null ? other.getDailyqtylimit() == null : this.getDailyqtylimit().equals(other.getDailyqtylimit()))
            && (this.getExpirydate() == null ? other.getExpirydate() == null : this.getExpirydate().equals(other.getExpirydate()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getMarginpercent() == null ? other.getMarginpercent() == null : this.getMarginpercent().equals(other.getMarginpercent()))
            && (this.getSeries() == null ? other.getSeries() == null : this.getSeries().equals(other.getSeries()))
            && (this.getPricecap() == null ? other.getPricecap() == null : this.getPricecap().equals(other.getPricecap()))
            && (this.getCalculationprice() == null ? other.getCalculationprice() == null : this.getCalculationprice().equals(other.getCalculationprice()))
            && (this.getSuspended() == null ? other.getSuspended() == null : this.getSuspended().equals(other.getSuspended()))
            && (this.getTradingccy() == null ? other.getTradingccy() == null : this.getTradingccy().equals(other.getTradingccy()))
            && (this.getExchangecode() == null ? other.getExchangecode() == null : this.getExchangecode().equals(other.getExchangecode()))
            && (this.getExchangeinternalcode() == null ? other.getExchangeinternalcode() == null : this.getExchangeinternalcode().equals(other.getExchangeinternalcode()))
            && (this.getBloomberg() == null ? other.getBloomberg() == null : this.getBloomberg().equals(other.getBloomberg()))
            && (this.getReuter() == null ? other.getReuter() == null : this.getReuter().equals(other.getReuter()))
            && (this.getIsin() == null ? other.getIsin() == null : this.getIsin().equals(other.getIsin()))
            && (this.getSedol() == null ? other.getSedol() == null : this.getSedol().equals(other.getSedol()))
            && (this.getFirstdealingdate() == null ? other.getFirstdealingdate() == null : this.getFirstdealingdate().equals(other.getFirstdealingdate()))
            && (this.getLastdealingdate() == null ? other.getLastdealingdate() == null : this.getLastdealingdate().equals(other.getLastdealingdate()))
            && (this.getElectronicclearing() == null ? other.getElectronicclearing() == null : this.getElectronicclearing().equals(other.getElectronicclearing()))
            && (this.getShortsell() == null ? other.getShortsell() == null : this.getShortsell().equals(other.getShortsell()))
            && (this.getParvalue() == null ? other.getParvalue() == null : this.getParvalue().equals(other.getParvalue()))
            && (this.getFee1() == null ? other.getFee1() == null : this.getFee1().equals(other.getFee1()))
            && (this.getFee2() == null ? other.getFee2() == null : this.getFee2().equals(other.getFee2()))
            && (this.getFee3() == null ? other.getFee3() == null : this.getFee3().equals(other.getFee3()))
            && (this.getFee4() == null ? other.getFee4() == null : this.getFee4().equals(other.getFee4()))
            && (this.getFee5() == null ? other.getFee5() == null : this.getFee5().equals(other.getFee5()))
            && (this.getFee6() == null ? other.getFee6() == null : this.getFee6().equals(other.getFee6()))
            && (this.getFee7() == null ? other.getFee7() == null : this.getFee7().equals(other.getFee7()))
            && (this.getFee8() == null ? other.getFee8() == null : this.getFee8().equals(other.getFee8()))
            && (this.getFee9() == null ? other.getFee9() == null : this.getFee9().equals(other.getFee9()))
            && (this.getFee10() == null ? other.getFee10() == null : this.getFee10().equals(other.getFee10()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getSpreadtablecode() == null ? other.getSpreadtablecode() == null : this.getSpreadtablecode().equals(other.getSpreadtablecode()))
            && (this.getStatusflag() == null ? other.getStatusflag() == null : this.getStatusflag().equals(other.getStatusflag()))
            && (this.getInstrumenttype() == null ? other.getInstrumenttype() == null : this.getInstrumenttype().equals(other.getInstrumenttype()))
            && (this.getDateoflisted() == null ? other.getDateoflisted() == null : this.getDateoflisted().equals(other.getDateoflisted()))
            && (this.getIlliquidcollateralcalculation() == null ? other.getIlliquidcollateralcalculation() == null : this.getIlliquidcollateralcalculation().equals(other.getIlliquidcollateralcalculation()))
            && (this.getSyncref() == null ? other.getSyncref() == null : this.getSyncref().equals(other.getSyncref()))
            && (this.getUndermarket() == null ? other.getUndermarket() == null : this.getUndermarket().equals(other.getUndermarket()))
            && (this.getUnderstock() == null ? other.getUnderstock() == null : this.getUnderstock().equals(other.getUnderstock()))
            && (this.getSuspendfrom() == null ? other.getSuspendfrom() == null : this.getSuspendfrom().equals(other.getSuspendfrom()))
            && (this.getLastsuspendprice() == null ? other.getLastsuspendprice() == null : this.getLastsuspendprice().equals(other.getLastsuspendprice()))
            && (this.getInstdepotcode() == null ? other.getInstdepotcode() == null : this.getInstdepotcode().equals(other.getInstdepotcode()))
            && (this.getInstlocation() == null ? other.getInstlocation() == null : this.getInstlocation().equals(other.getInstlocation()))
            && (this.getNavdate() == null ? other.getNavdate() == null : this.getNavdate().equals(other.getNavdate()))
            && (this.getCollateralratio() == null ? other.getCollateralratio() == null : this.getCollateralratio().equals(other.getCollateralratio()))
            && (this.getInterestratecategory() == null ? other.getInterestratecategory() == null : this.getInterestratecategory().equals(other.getInterestratecategory()))
            && (this.getNobuy() == null ? other.getNobuy() == null : this.getNobuy().equals(other.getNobuy()))
            && (this.getNosell() == null ? other.getNosell() == null : this.getNosell().equals(other.getNosell()))
            && (this.getSellonlybycsc() == null ? other.getSellonlybycsc() == null : this.getSellonlybycsc().equals(other.getSellonlybycsc()))
            && (this.getGlobalinstrumenttype() == null ? other.getGlobalinstrumenttype() == null : this.getGlobalinstrumenttype().equals(other.getGlobalinstrumenttype()))
            && (this.getIdcinstrumenttype() == null ? other.getIdcinstrumenttype() == null : this.getIdcinstrumenttype().equals(other.getIdcinstrumenttype()))
            && (this.getTier() == null ? other.getTier() == null : this.getTier().equals(other.getTier()))
            && (this.getLogdatetime() == null ? other.getLogdatetime() == null : this.getLogdatetime().equals(other.getLogdatetime()))
            && (this.getLoghostname() == null ? other.getLoghostname() == null : this.getLoghostname().equals(other.getLoghostname()))
            && (this.getLogusername() == null ? other.getLogusername() == null : this.getLogusername().equals(other.getLogusername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getInstrument() == null) ? 0 : getInstrument().hashCode());
        result = prime * result + ((getMarket() == null) ? 0 : getMarket().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getShortname() == null) ? 0 : getShortname().hashCode());
        result = prime * result + ((getCname() == null) ? 0 : getCname().hashCode());
        result = prime * result + ((getCshortname() == null) ? 0 : getCshortname().hashCode());
        result = prime * result + ((getInstrumentclass() == null) ? 0 : getInstrumentclass().hashCode());
        result = prime * result + ((getProdcode() == null) ? 0 : getProdcode().hashCode());
        result = prime * result + ((getLotsize() == null) ? 0 : getLotsize().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getTransactionvaluelimit() == null) ? 0 : getTransactionvaluelimit().hashCode());
        result = prime * result + ((getTransactionqtylimit() == null) ? 0 : getTransactionqtylimit().hashCode());
        result = prime * result + ((getDailyvaluelimit() == null) ? 0 : getDailyvaluelimit().hashCode());
        result = prime * result + ((getDailyqtylimit() == null) ? 0 : getDailyqtylimit().hashCode());
        result = prime * result + ((getExpirydate() == null) ? 0 : getExpirydate().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getMarginpercent() == null) ? 0 : getMarginpercent().hashCode());
        result = prime * result + ((getSeries() == null) ? 0 : getSeries().hashCode());
        result = prime * result + ((getPricecap() == null) ? 0 : getPricecap().hashCode());
        result = prime * result + ((getCalculationprice() == null) ? 0 : getCalculationprice().hashCode());
        result = prime * result + ((getSuspended() == null) ? 0 : getSuspended().hashCode());
        result = prime * result + ((getTradingccy() == null) ? 0 : getTradingccy().hashCode());
        result = prime * result + ((getExchangecode() == null) ? 0 : getExchangecode().hashCode());
        result = prime * result + ((getExchangeinternalcode() == null) ? 0 : getExchangeinternalcode().hashCode());
        result = prime * result + ((getBloomberg() == null) ? 0 : getBloomberg().hashCode());
        result = prime * result + ((getReuter() == null) ? 0 : getReuter().hashCode());
        result = prime * result + ((getIsin() == null) ? 0 : getIsin().hashCode());
        result = prime * result + ((getSedol() == null) ? 0 : getSedol().hashCode());
        result = prime * result + ((getFirstdealingdate() == null) ? 0 : getFirstdealingdate().hashCode());
        result = prime * result + ((getLastdealingdate() == null) ? 0 : getLastdealingdate().hashCode());
        result = prime * result + ((getElectronicclearing() == null) ? 0 : getElectronicclearing().hashCode());
        result = prime * result + ((getShortsell() == null) ? 0 : getShortsell().hashCode());
        result = prime * result + ((getParvalue() == null) ? 0 : getParvalue().hashCode());
        result = prime * result + ((getFee1() == null) ? 0 : getFee1().hashCode());
        result = prime * result + ((getFee2() == null) ? 0 : getFee2().hashCode());
        result = prime * result + ((getFee3() == null) ? 0 : getFee3().hashCode());
        result = prime * result + ((getFee4() == null) ? 0 : getFee4().hashCode());
        result = prime * result + ((getFee5() == null) ? 0 : getFee5().hashCode());
        result = prime * result + ((getFee6() == null) ? 0 : getFee6().hashCode());
        result = prime * result + ((getFee7() == null) ? 0 : getFee7().hashCode());
        result = prime * result + ((getFee8() == null) ? 0 : getFee8().hashCode());
        result = prime * result + ((getFee9() == null) ? 0 : getFee9().hashCode());
        result = prime * result + ((getFee10() == null) ? 0 : getFee10().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getSpreadtablecode() == null) ? 0 : getSpreadtablecode().hashCode());
        result = prime * result + ((getStatusflag() == null) ? 0 : getStatusflag().hashCode());
        result = prime * result + ((getInstrumenttype() == null) ? 0 : getInstrumenttype().hashCode());
        result = prime * result + ((getDateoflisted() == null) ? 0 : getDateoflisted().hashCode());
        result = prime * result + ((getIlliquidcollateralcalculation() == null) ? 0 : getIlliquidcollateralcalculation().hashCode());
        result = prime * result + ((getSyncref() == null) ? 0 : getSyncref().hashCode());
        result = prime * result + ((getUndermarket() == null) ? 0 : getUndermarket().hashCode());
        result = prime * result + ((getUnderstock() == null) ? 0 : getUnderstock().hashCode());
        result = prime * result + ((getSuspendfrom() == null) ? 0 : getSuspendfrom().hashCode());
        result = prime * result + ((getLastsuspendprice() == null) ? 0 : getLastsuspendprice().hashCode());
        result = prime * result + ((getInstdepotcode() == null) ? 0 : getInstdepotcode().hashCode());
        result = prime * result + ((getInstlocation() == null) ? 0 : getInstlocation().hashCode());
        result = prime * result + ((getNavdate() == null) ? 0 : getNavdate().hashCode());
        result = prime * result + ((getCollateralratio() == null) ? 0 : getCollateralratio().hashCode());
        result = prime * result + ((getInterestratecategory() == null) ? 0 : getInterestratecategory().hashCode());
        result = prime * result + ((getNobuy() == null) ? 0 : getNobuy().hashCode());
        result = prime * result + ((getNosell() == null) ? 0 : getNosell().hashCode());
        result = prime * result + ((getSellonlybycsc() == null) ? 0 : getSellonlybycsc().hashCode());
        result = prime * result + ((getGlobalinstrumenttype() == null) ? 0 : getGlobalinstrumenttype().hashCode());
        result = prime * result + ((getIdcinstrumenttype() == null) ? 0 : getIdcinstrumenttype().hashCode());
        result = prime * result + ((getTier() == null) ? 0 : getTier().hashCode());
        result = prime * result + ((getLogdatetime() == null) ? 0 : getLogdatetime().hashCode());
        result = prime * result + ((getLoghostname() == null) ? 0 : getLoghostname().hashCode());
        result = prime * result + ((getLogusername() == null) ? 0 : getLogusername().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentVersion
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", date=").append(date);
        sb.append(", instrument=").append(instrument);
        sb.append(", market=").append(market);
        sb.append(", name=").append(name);
        sb.append(", shortname=").append(shortname);
        sb.append(", cname=").append(cname);
        sb.append(", cshortname=").append(cshortname);
        sb.append(", instrumentclass=").append(instrumentclass);
        sb.append(", prodcode=").append(prodcode);
        sb.append(", lotsize=").append(lotsize);
        sb.append(", price=").append(price);
        sb.append(", transactionvaluelimit=").append(transactionvaluelimit);
        sb.append(", transactionqtylimit=").append(transactionqtylimit);
        sb.append(", dailyvaluelimit=").append(dailyvaluelimit);
        sb.append(", dailyqtylimit=").append(dailyqtylimit);
        sb.append(", expirydate=").append(expirydate);
        sb.append(", active=").append(active);
        sb.append(", marginpercent=").append(marginpercent);
        sb.append(", series=").append(series);
        sb.append(", pricecap=").append(pricecap);
        sb.append(", calculationprice=").append(calculationprice);
        sb.append(", suspended=").append(suspended);
        sb.append(", tradingccy=").append(tradingccy);
        sb.append(", exchangecode=").append(exchangecode);
        sb.append(", exchangeinternalcode=").append(exchangeinternalcode);
        sb.append(", bloomberg=").append(bloomberg);
        sb.append(", reuter=").append(reuter);
        sb.append(", isin=").append(isin);
        sb.append(", sedol=").append(sedol);
        sb.append(", firstdealingdate=").append(firstdealingdate);
        sb.append(", lastdealingdate=").append(lastdealingdate);
        sb.append(", electronicclearing=").append(electronicclearing);
        sb.append(", shortsell=").append(shortsell);
        sb.append(", parvalue=").append(parvalue);
        sb.append(", fee1=").append(fee1);
        sb.append(", fee2=").append(fee2);
        sb.append(", fee3=").append(fee3);
        sb.append(", fee4=").append(fee4);
        sb.append(", fee5=").append(fee5);
        sb.append(", fee6=").append(fee6);
        sb.append(", fee7=").append(fee7);
        sb.append(", fee8=").append(fee8);
        sb.append(", fee9=").append(fee9);
        sb.append(", fee10=").append(fee10);
        sb.append(", category=").append(category);
        sb.append(", spreadtablecode=").append(spreadtablecode);
        sb.append(", statusflag=").append(statusflag);
        sb.append(", instrumenttype=").append(instrumenttype);
        sb.append(", dateoflisted=").append(dateoflisted);
        sb.append(", illiquidcollateralcalculation=").append(illiquidcollateralcalculation);
        sb.append(", syncref=").append(syncref);
        sb.append(", undermarket=").append(undermarket);
        sb.append(", understock=").append(understock);
        sb.append(", suspendfrom=").append(suspendfrom);
        sb.append(", lastsuspendprice=").append(lastsuspendprice);
        sb.append(", instdepotcode=").append(instdepotcode);
        sb.append(", instlocation=").append(instlocation);
        sb.append(", navdate=").append(navdate);
        sb.append(", collateralratio=").append(collateralratio);
        sb.append(", interestratecategory=").append(interestratecategory);
        sb.append(", nobuy=").append(nobuy);
        sb.append(", nosell=").append(nosell);
        sb.append(", sellonlybycsc=").append(sellonlybycsc);
        sb.append(", globalinstrumenttype=").append(globalinstrumenttype);
        sb.append(", idcinstrumenttype=").append(idcinstrumenttype);
        sb.append(", tier=").append(tier);
        sb.append(", logdatetime=").append(logdatetime);
        sb.append(", loghostname=").append(loghostname);
        sb.append(", logusername=").append(logusername);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}