package com.example.migration.dao.master.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table InstrumentExtVersion
 */
public class InstrumentExtVersion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.Date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.Instrument
     *
     * @mbg.generated
     */
    private String instrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.Market
     *
     * @mbg.generated
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.DefaultChargeCCY
     *
     * @mbg.generated
     */
    private String defaultchargeccy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.CouponRate
     *
     * @mbg.generated
     */
    private BigDecimal couponrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.PriceInPercentOrAmount
     *
     * @mbg.generated
     */
    private String priceinpercentoramount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.LastCouponDate
     *
     * @mbg.generated
     */
    private Date lastcoupondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.NextCouponDate
     *
     * @mbg.generated
     */
    private Date nextcoupondate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.FundHouse
     *
     * @mbg.generated
     */
    private String fundhouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.TotalIssuedShares
     *
     * @mbg.generated
     */
    private BigDecimal totalissuedshares;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.InstrumentSection
     *
     * @mbg.generated
     */
    private String instrumentsection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.CouponPeriod
     *
     * @mbg.generated
     */
    private String couponperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.RatePeriod
     *
     * @mbg.generated
     */
    private Integer rateperiod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ConvertInstrument
     *
     * @mbg.generated
     */
    private String convertinstrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ConvertMarket
     *
     * @mbg.generated
     */
    private String convertmarket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ConvertDepot
     *
     * @mbg.generated
     */
    private String convertdepot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ConvertLocation
     *
     * @mbg.generated
     */
    private String convertlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ConfirmDays
     *
     * @mbg.generated
     */
    private Integer confirmdays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.SettleDays
     *
     * @mbg.generated
     */
    private Integer settledays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ELIType
     *
     * @mbg.generated
     */
    private String elitype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.IssuePrice
     *
     * @mbg.generated
     */
    private BigDecimal issueprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.StrikePrice
     *
     * @mbg.generated
     */
    private BigDecimal strikeprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.StrikePriceUpper
     *
     * @mbg.generated
     */
    private BigDecimal strikepriceupper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.SettleMode
     *
     * @mbg.generated
     */
    private String settlemode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.InstSettleDate
     *
     * @mbg.generated
     */
    private Date instsettledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.Issuer
     *
     * @mbg.generated
     */
    private String issuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.UnitRounding
     *
     * @mbg.generated
     */
    private Integer unitrounding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.RoundingType
     *
     * @mbg.generated
     */
    private String roundingtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.FundHouseFee
     *
     * @mbg.generated
     */
    private BigDecimal fundhousefee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.AdditionalFee
     *
     * @mbg.generated
     */
    private BigDecimal additionalfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.MinRedemptedAmount
     *
     * @mbg.generated
     */
    private BigDecimal minredemptedamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.MinRemainingAmount
     *
     * @mbg.generated
     */
    private BigDecimal minremainingamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.ShortTradeDays
     *
     * @mbg.generated
     */
    private Integer shorttradedays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.SyncRef
     *
     * @mbg.generated
     */
    private String syncref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.UnderIndex
     *
     * @mbg.generated
     */
    private String underindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.CallPrice
     *
     * @mbg.generated
     */
    private BigDecimal callprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.AAStocks
     *
     * @mbg.generated
     */
    private String aastocks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.PSHK
     *
     * @mbg.generated
     */
    private String pshk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.IsStaffExemption
     *
     * @mbg.generated
     */
    private String isstaffexemption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.VirtualAsset
     *
     * @mbg.generated
     */
    private String virtualasset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.LogDateTime
     *
     * @mbg.generated
     */
    private Date logdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.LogHostName
     *
     * @mbg.generated
     */
    private String loghostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column InstrumentExtVersion.LogUserName
     *
     * @mbg.generated
     */
    private String logusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.Date
     *
     * @return the value of InstrumentExtVersion.Date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.Date
     *
     * @param date the value for InstrumentExtVersion.Date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.Instrument
     *
     * @return the value of InstrumentExtVersion.Instrument
     *
     * @mbg.generated
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.Instrument
     *
     * @param instrument the value for InstrumentExtVersion.Instrument
     *
     * @mbg.generated
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument == null ? null : instrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.Market
     *
     * @return the value of InstrumentExtVersion.Market
     *
     * @mbg.generated
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.Market
     *
     * @param market the value for InstrumentExtVersion.Market
     *
     * @mbg.generated
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.DefaultChargeCCY
     *
     * @return the value of InstrumentExtVersion.DefaultChargeCCY
     *
     * @mbg.generated
     */
    public String getDefaultchargeccy() {
        return defaultchargeccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.DefaultChargeCCY
     *
     * @param defaultchargeccy the value for InstrumentExtVersion.DefaultChargeCCY
     *
     * @mbg.generated
     */
    public void setDefaultchargeccy(String defaultchargeccy) {
        this.defaultchargeccy = defaultchargeccy == null ? null : defaultchargeccy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.CouponRate
     *
     * @return the value of InstrumentExtVersion.CouponRate
     *
     * @mbg.generated
     */
    public BigDecimal getCouponrate() {
        return couponrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.CouponRate
     *
     * @param couponrate the value for InstrumentExtVersion.CouponRate
     *
     * @mbg.generated
     */
    public void setCouponrate(BigDecimal couponrate) {
        this.couponrate = couponrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.PriceInPercentOrAmount
     *
     * @return the value of InstrumentExtVersion.PriceInPercentOrAmount
     *
     * @mbg.generated
     */
    public String getPriceinpercentoramount() {
        return priceinpercentoramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.PriceInPercentOrAmount
     *
     * @param priceinpercentoramount the value for InstrumentExtVersion.PriceInPercentOrAmount
     *
     * @mbg.generated
     */
    public void setPriceinpercentoramount(String priceinpercentoramount) {
        this.priceinpercentoramount = priceinpercentoramount == null ? null : priceinpercentoramount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.LastCouponDate
     *
     * @return the value of InstrumentExtVersion.LastCouponDate
     *
     * @mbg.generated
     */
    public Date getLastcoupondate() {
        return lastcoupondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.LastCouponDate
     *
     * @param lastcoupondate the value for InstrumentExtVersion.LastCouponDate
     *
     * @mbg.generated
     */
    public void setLastcoupondate(Date lastcoupondate) {
        this.lastcoupondate = lastcoupondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.NextCouponDate
     *
     * @return the value of InstrumentExtVersion.NextCouponDate
     *
     * @mbg.generated
     */
    public Date getNextcoupondate() {
        return nextcoupondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.NextCouponDate
     *
     * @param nextcoupondate the value for InstrumentExtVersion.NextCouponDate
     *
     * @mbg.generated
     */
    public void setNextcoupondate(Date nextcoupondate) {
        this.nextcoupondate = nextcoupondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.FundHouse
     *
     * @return the value of InstrumentExtVersion.FundHouse
     *
     * @mbg.generated
     */
    public String getFundhouse() {
        return fundhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.FundHouse
     *
     * @param fundhouse the value for InstrumentExtVersion.FundHouse
     *
     * @mbg.generated
     */
    public void setFundhouse(String fundhouse) {
        this.fundhouse = fundhouse == null ? null : fundhouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.TotalIssuedShares
     *
     * @return the value of InstrumentExtVersion.TotalIssuedShares
     *
     * @mbg.generated
     */
    public BigDecimal getTotalissuedshares() {
        return totalissuedshares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.TotalIssuedShares
     *
     * @param totalissuedshares the value for InstrumentExtVersion.TotalIssuedShares
     *
     * @mbg.generated
     */
    public void setTotalissuedshares(BigDecimal totalissuedshares) {
        this.totalissuedshares = totalissuedshares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.InstrumentSection
     *
     * @return the value of InstrumentExtVersion.InstrumentSection
     *
     * @mbg.generated
     */
    public String getInstrumentsection() {
        return instrumentsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.InstrumentSection
     *
     * @param instrumentsection the value for InstrumentExtVersion.InstrumentSection
     *
     * @mbg.generated
     */
    public void setInstrumentsection(String instrumentsection) {
        this.instrumentsection = instrumentsection == null ? null : instrumentsection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.CouponPeriod
     *
     * @return the value of InstrumentExtVersion.CouponPeriod
     *
     * @mbg.generated
     */
    public String getCouponperiod() {
        return couponperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.CouponPeriod
     *
     * @param couponperiod the value for InstrumentExtVersion.CouponPeriod
     *
     * @mbg.generated
     */
    public void setCouponperiod(String couponperiod) {
        this.couponperiod = couponperiod == null ? null : couponperiod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.RatePeriod
     *
     * @return the value of InstrumentExtVersion.RatePeriod
     *
     * @mbg.generated
     */
    public Integer getRateperiod() {
        return rateperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.RatePeriod
     *
     * @param rateperiod the value for InstrumentExtVersion.RatePeriod
     *
     * @mbg.generated
     */
    public void setRateperiod(Integer rateperiod) {
        this.rateperiod = rateperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ConvertInstrument
     *
     * @return the value of InstrumentExtVersion.ConvertInstrument
     *
     * @mbg.generated
     */
    public String getConvertinstrument() {
        return convertinstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ConvertInstrument
     *
     * @param convertinstrument the value for InstrumentExtVersion.ConvertInstrument
     *
     * @mbg.generated
     */
    public void setConvertinstrument(String convertinstrument) {
        this.convertinstrument = convertinstrument == null ? null : convertinstrument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ConvertMarket
     *
     * @return the value of InstrumentExtVersion.ConvertMarket
     *
     * @mbg.generated
     */
    public String getConvertmarket() {
        return convertmarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ConvertMarket
     *
     * @param convertmarket the value for InstrumentExtVersion.ConvertMarket
     *
     * @mbg.generated
     */
    public void setConvertmarket(String convertmarket) {
        this.convertmarket = convertmarket == null ? null : convertmarket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ConvertDepot
     *
     * @return the value of InstrumentExtVersion.ConvertDepot
     *
     * @mbg.generated
     */
    public String getConvertdepot() {
        return convertdepot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ConvertDepot
     *
     * @param convertdepot the value for InstrumentExtVersion.ConvertDepot
     *
     * @mbg.generated
     */
    public void setConvertdepot(String convertdepot) {
        this.convertdepot = convertdepot == null ? null : convertdepot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ConvertLocation
     *
     * @return the value of InstrumentExtVersion.ConvertLocation
     *
     * @mbg.generated
     */
    public String getConvertlocation() {
        return convertlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ConvertLocation
     *
     * @param convertlocation the value for InstrumentExtVersion.ConvertLocation
     *
     * @mbg.generated
     */
    public void setConvertlocation(String convertlocation) {
        this.convertlocation = convertlocation == null ? null : convertlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ConfirmDays
     *
     * @return the value of InstrumentExtVersion.ConfirmDays
     *
     * @mbg.generated
     */
    public Integer getConfirmdays() {
        return confirmdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ConfirmDays
     *
     * @param confirmdays the value for InstrumentExtVersion.ConfirmDays
     *
     * @mbg.generated
     */
    public void setConfirmdays(Integer confirmdays) {
        this.confirmdays = confirmdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.SettleDays
     *
     * @return the value of InstrumentExtVersion.SettleDays
     *
     * @mbg.generated
     */
    public Integer getSettledays() {
        return settledays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.SettleDays
     *
     * @param settledays the value for InstrumentExtVersion.SettleDays
     *
     * @mbg.generated
     */
    public void setSettledays(Integer settledays) {
        this.settledays = settledays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ELIType
     *
     * @return the value of InstrumentExtVersion.ELIType
     *
     * @mbg.generated
     */
    public String getElitype() {
        return elitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ELIType
     *
     * @param elitype the value for InstrumentExtVersion.ELIType
     *
     * @mbg.generated
     */
    public void setElitype(String elitype) {
        this.elitype = elitype == null ? null : elitype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.IssuePrice
     *
     * @return the value of InstrumentExtVersion.IssuePrice
     *
     * @mbg.generated
     */
    public BigDecimal getIssueprice() {
        return issueprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.IssuePrice
     *
     * @param issueprice the value for InstrumentExtVersion.IssuePrice
     *
     * @mbg.generated
     */
    public void setIssueprice(BigDecimal issueprice) {
        this.issueprice = issueprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.StrikePrice
     *
     * @return the value of InstrumentExtVersion.StrikePrice
     *
     * @mbg.generated
     */
    public BigDecimal getStrikeprice() {
        return strikeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.StrikePrice
     *
     * @param strikeprice the value for InstrumentExtVersion.StrikePrice
     *
     * @mbg.generated
     */
    public void setStrikeprice(BigDecimal strikeprice) {
        this.strikeprice = strikeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.StrikePriceUpper
     *
     * @return the value of InstrumentExtVersion.StrikePriceUpper
     *
     * @mbg.generated
     */
    public BigDecimal getStrikepriceupper() {
        return strikepriceupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.StrikePriceUpper
     *
     * @param strikepriceupper the value for InstrumentExtVersion.StrikePriceUpper
     *
     * @mbg.generated
     */
    public void setStrikepriceupper(BigDecimal strikepriceupper) {
        this.strikepriceupper = strikepriceupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.SettleMode
     *
     * @return the value of InstrumentExtVersion.SettleMode
     *
     * @mbg.generated
     */
    public String getSettlemode() {
        return settlemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.SettleMode
     *
     * @param settlemode the value for InstrumentExtVersion.SettleMode
     *
     * @mbg.generated
     */
    public void setSettlemode(String settlemode) {
        this.settlemode = settlemode == null ? null : settlemode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.InstSettleDate
     *
     * @return the value of InstrumentExtVersion.InstSettleDate
     *
     * @mbg.generated
     */
    public Date getInstsettledate() {
        return instsettledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.InstSettleDate
     *
     * @param instsettledate the value for InstrumentExtVersion.InstSettleDate
     *
     * @mbg.generated
     */
    public void setInstsettledate(Date instsettledate) {
        this.instsettledate = instsettledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.Issuer
     *
     * @return the value of InstrumentExtVersion.Issuer
     *
     * @mbg.generated
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.Issuer
     *
     * @param issuer the value for InstrumentExtVersion.Issuer
     *
     * @mbg.generated
     */
    public void setIssuer(String issuer) {
        this.issuer = issuer == null ? null : issuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.UnitRounding
     *
     * @return the value of InstrumentExtVersion.UnitRounding
     *
     * @mbg.generated
     */
    public Integer getUnitrounding() {
        return unitrounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.UnitRounding
     *
     * @param unitrounding the value for InstrumentExtVersion.UnitRounding
     *
     * @mbg.generated
     */
    public void setUnitrounding(Integer unitrounding) {
        this.unitrounding = unitrounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.RoundingType
     *
     * @return the value of InstrumentExtVersion.RoundingType
     *
     * @mbg.generated
     */
    public String getRoundingtype() {
        return roundingtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.RoundingType
     *
     * @param roundingtype the value for InstrumentExtVersion.RoundingType
     *
     * @mbg.generated
     */
    public void setRoundingtype(String roundingtype) {
        this.roundingtype = roundingtype == null ? null : roundingtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.FundHouseFee
     *
     * @return the value of InstrumentExtVersion.FundHouseFee
     *
     * @mbg.generated
     */
    public BigDecimal getFundhousefee() {
        return fundhousefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.FundHouseFee
     *
     * @param fundhousefee the value for InstrumentExtVersion.FundHouseFee
     *
     * @mbg.generated
     */
    public void setFundhousefee(BigDecimal fundhousefee) {
        this.fundhousefee = fundhousefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.AdditionalFee
     *
     * @return the value of InstrumentExtVersion.AdditionalFee
     *
     * @mbg.generated
     */
    public BigDecimal getAdditionalfee() {
        return additionalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.AdditionalFee
     *
     * @param additionalfee the value for InstrumentExtVersion.AdditionalFee
     *
     * @mbg.generated
     */
    public void setAdditionalfee(BigDecimal additionalfee) {
        this.additionalfee = additionalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.MinRedemptedAmount
     *
     * @return the value of InstrumentExtVersion.MinRedemptedAmount
     *
     * @mbg.generated
     */
    public BigDecimal getMinredemptedamount() {
        return minredemptedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.MinRedemptedAmount
     *
     * @param minredemptedamount the value for InstrumentExtVersion.MinRedemptedAmount
     *
     * @mbg.generated
     */
    public void setMinredemptedamount(BigDecimal minredemptedamount) {
        this.minredemptedamount = minredemptedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.MinRemainingAmount
     *
     * @return the value of InstrumentExtVersion.MinRemainingAmount
     *
     * @mbg.generated
     */
    public BigDecimal getMinremainingamount() {
        return minremainingamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.MinRemainingAmount
     *
     * @param minremainingamount the value for InstrumentExtVersion.MinRemainingAmount
     *
     * @mbg.generated
     */
    public void setMinremainingamount(BigDecimal minremainingamount) {
        this.minremainingamount = minremainingamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.ShortTradeDays
     *
     * @return the value of InstrumentExtVersion.ShortTradeDays
     *
     * @mbg.generated
     */
    public Integer getShorttradedays() {
        return shorttradedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.ShortTradeDays
     *
     * @param shorttradedays the value for InstrumentExtVersion.ShortTradeDays
     *
     * @mbg.generated
     */
    public void setShorttradedays(Integer shorttradedays) {
        this.shorttradedays = shorttradedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.SyncRef
     *
     * @return the value of InstrumentExtVersion.SyncRef
     *
     * @mbg.generated
     */
    public String getSyncref() {
        return syncref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.SyncRef
     *
     * @param syncref the value for InstrumentExtVersion.SyncRef
     *
     * @mbg.generated
     */
    public void setSyncref(String syncref) {
        this.syncref = syncref == null ? null : syncref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.UnderIndex
     *
     * @return the value of InstrumentExtVersion.UnderIndex
     *
     * @mbg.generated
     */
    public String getUnderindex() {
        return underindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.UnderIndex
     *
     * @param underindex the value for InstrumentExtVersion.UnderIndex
     *
     * @mbg.generated
     */
    public void setUnderindex(String underindex) {
        this.underindex = underindex == null ? null : underindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.CallPrice
     *
     * @return the value of InstrumentExtVersion.CallPrice
     *
     * @mbg.generated
     */
    public BigDecimal getCallprice() {
        return callprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.CallPrice
     *
     * @param callprice the value for InstrumentExtVersion.CallPrice
     *
     * @mbg.generated
     */
    public void setCallprice(BigDecimal callprice) {
        this.callprice = callprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.AAStocks
     *
     * @return the value of InstrumentExtVersion.AAStocks
     *
     * @mbg.generated
     */
    public String getAastocks() {
        return aastocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.AAStocks
     *
     * @param aastocks the value for InstrumentExtVersion.AAStocks
     *
     * @mbg.generated
     */
    public void setAastocks(String aastocks) {
        this.aastocks = aastocks == null ? null : aastocks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.PSHK
     *
     * @return the value of InstrumentExtVersion.PSHK
     *
     * @mbg.generated
     */
    public String getPshk() {
        return pshk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.PSHK
     *
     * @param pshk the value for InstrumentExtVersion.PSHK
     *
     * @mbg.generated
     */
    public void setPshk(String pshk) {
        this.pshk = pshk == null ? null : pshk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.IsStaffExemption
     *
     * @return the value of InstrumentExtVersion.IsStaffExemption
     *
     * @mbg.generated
     */
    public String getIsstaffexemption() {
        return isstaffexemption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.IsStaffExemption
     *
     * @param isstaffexemption the value for InstrumentExtVersion.IsStaffExemption
     *
     * @mbg.generated
     */
    public void setIsstaffexemption(String isstaffexemption) {
        this.isstaffexemption = isstaffexemption == null ? null : isstaffexemption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.VirtualAsset
     *
     * @return the value of InstrumentExtVersion.VirtualAsset
     *
     * @mbg.generated
     */
    public String getVirtualasset() {
        return virtualasset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.VirtualAsset
     *
     * @param virtualasset the value for InstrumentExtVersion.VirtualAsset
     *
     * @mbg.generated
     */
    public void setVirtualasset(String virtualasset) {
        this.virtualasset = virtualasset == null ? null : virtualasset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.LogDateTime
     *
     * @return the value of InstrumentExtVersion.LogDateTime
     *
     * @mbg.generated
     */
    public Date getLogdatetime() {
        return logdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.LogDateTime
     *
     * @param logdatetime the value for InstrumentExtVersion.LogDateTime
     *
     * @mbg.generated
     */
    public void setLogdatetime(Date logdatetime) {
        this.logdatetime = logdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.LogHostName
     *
     * @return the value of InstrumentExtVersion.LogHostName
     *
     * @mbg.generated
     */
    public String getLoghostname() {
        return loghostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.LogHostName
     *
     * @param loghostname the value for InstrumentExtVersion.LogHostName
     *
     * @mbg.generated
     */
    public void setLoghostname(String loghostname) {
        this.loghostname = loghostname == null ? null : loghostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column InstrumentExtVersion.LogUserName
     *
     * @return the value of InstrumentExtVersion.LogUserName
     *
     * @mbg.generated
     */
    public String getLogusername() {
        return logusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column InstrumentExtVersion.LogUserName
     *
     * @param logusername the value for InstrumentExtVersion.LogUserName
     *
     * @mbg.generated
     */
    public void setLogusername(String logusername) {
        this.logusername = logusername == null ? null : logusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InstrumentExtVersion other = (InstrumentExtVersion) that;
        return (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getInstrument() == null ? other.getInstrument() == null : this.getInstrument().equals(other.getInstrument()))
            && (this.getMarket() == null ? other.getMarket() == null : this.getMarket().equals(other.getMarket()))
            && (this.getDefaultchargeccy() == null ? other.getDefaultchargeccy() == null : this.getDefaultchargeccy().equals(other.getDefaultchargeccy()))
            && (this.getCouponrate() == null ? other.getCouponrate() == null : this.getCouponrate().equals(other.getCouponrate()))
            && (this.getPriceinpercentoramount() == null ? other.getPriceinpercentoramount() == null : this.getPriceinpercentoramount().equals(other.getPriceinpercentoramount()))
            && (this.getLastcoupondate() == null ? other.getLastcoupondate() == null : this.getLastcoupondate().equals(other.getLastcoupondate()))
            && (this.getNextcoupondate() == null ? other.getNextcoupondate() == null : this.getNextcoupondate().equals(other.getNextcoupondate()))
            && (this.getFundhouse() == null ? other.getFundhouse() == null : this.getFundhouse().equals(other.getFundhouse()))
            && (this.getTotalissuedshares() == null ? other.getTotalissuedshares() == null : this.getTotalissuedshares().equals(other.getTotalissuedshares()))
            && (this.getInstrumentsection() == null ? other.getInstrumentsection() == null : this.getInstrumentsection().equals(other.getInstrumentsection()))
            && (this.getCouponperiod() == null ? other.getCouponperiod() == null : this.getCouponperiod().equals(other.getCouponperiod()))
            && (this.getRateperiod() == null ? other.getRateperiod() == null : this.getRateperiod().equals(other.getRateperiod()))
            && (this.getConvertinstrument() == null ? other.getConvertinstrument() == null : this.getConvertinstrument().equals(other.getConvertinstrument()))
            && (this.getConvertmarket() == null ? other.getConvertmarket() == null : this.getConvertmarket().equals(other.getConvertmarket()))
            && (this.getConvertdepot() == null ? other.getConvertdepot() == null : this.getConvertdepot().equals(other.getConvertdepot()))
            && (this.getConvertlocation() == null ? other.getConvertlocation() == null : this.getConvertlocation().equals(other.getConvertlocation()))
            && (this.getConfirmdays() == null ? other.getConfirmdays() == null : this.getConfirmdays().equals(other.getConfirmdays()))
            && (this.getSettledays() == null ? other.getSettledays() == null : this.getSettledays().equals(other.getSettledays()))
            && (this.getElitype() == null ? other.getElitype() == null : this.getElitype().equals(other.getElitype()))
            && (this.getIssueprice() == null ? other.getIssueprice() == null : this.getIssueprice().equals(other.getIssueprice()))
            && (this.getStrikeprice() == null ? other.getStrikeprice() == null : this.getStrikeprice().equals(other.getStrikeprice()))
            && (this.getStrikepriceupper() == null ? other.getStrikepriceupper() == null : this.getStrikepriceupper().equals(other.getStrikepriceupper()))
            && (this.getSettlemode() == null ? other.getSettlemode() == null : this.getSettlemode().equals(other.getSettlemode()))
            && (this.getInstsettledate() == null ? other.getInstsettledate() == null : this.getInstsettledate().equals(other.getInstsettledate()))
            && (this.getIssuer() == null ? other.getIssuer() == null : this.getIssuer().equals(other.getIssuer()))
            && (this.getUnitrounding() == null ? other.getUnitrounding() == null : this.getUnitrounding().equals(other.getUnitrounding()))
            && (this.getRoundingtype() == null ? other.getRoundingtype() == null : this.getRoundingtype().equals(other.getRoundingtype()))
            && (this.getFundhousefee() == null ? other.getFundhousefee() == null : this.getFundhousefee().equals(other.getFundhousefee()))
            && (this.getAdditionalfee() == null ? other.getAdditionalfee() == null : this.getAdditionalfee().equals(other.getAdditionalfee()))
            && (this.getMinredemptedamount() == null ? other.getMinredemptedamount() == null : this.getMinredemptedamount().equals(other.getMinredemptedamount()))
            && (this.getMinremainingamount() == null ? other.getMinremainingamount() == null : this.getMinremainingamount().equals(other.getMinremainingamount()))
            && (this.getShorttradedays() == null ? other.getShorttradedays() == null : this.getShorttradedays().equals(other.getShorttradedays()))
            && (this.getSyncref() == null ? other.getSyncref() == null : this.getSyncref().equals(other.getSyncref()))
            && (this.getUnderindex() == null ? other.getUnderindex() == null : this.getUnderindex().equals(other.getUnderindex()))
            && (this.getCallprice() == null ? other.getCallprice() == null : this.getCallprice().equals(other.getCallprice()))
            && (this.getAastocks() == null ? other.getAastocks() == null : this.getAastocks().equals(other.getAastocks()))
            && (this.getPshk() == null ? other.getPshk() == null : this.getPshk().equals(other.getPshk()))
            && (this.getIsstaffexemption() == null ? other.getIsstaffexemption() == null : this.getIsstaffexemption().equals(other.getIsstaffexemption()))
            && (this.getVirtualasset() == null ? other.getVirtualasset() == null : this.getVirtualasset().equals(other.getVirtualasset()))
            && (this.getLogdatetime() == null ? other.getLogdatetime() == null : this.getLogdatetime().equals(other.getLogdatetime()))
            && (this.getLoghostname() == null ? other.getLoghostname() == null : this.getLoghostname().equals(other.getLoghostname()))
            && (this.getLogusername() == null ? other.getLogusername() == null : this.getLogusername().equals(other.getLogusername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getInstrument() == null) ? 0 : getInstrument().hashCode());
        result = prime * result + ((getMarket() == null) ? 0 : getMarket().hashCode());
        result = prime * result + ((getDefaultchargeccy() == null) ? 0 : getDefaultchargeccy().hashCode());
        result = prime * result + ((getCouponrate() == null) ? 0 : getCouponrate().hashCode());
        result = prime * result + ((getPriceinpercentoramount() == null) ? 0 : getPriceinpercentoramount().hashCode());
        result = prime * result + ((getLastcoupondate() == null) ? 0 : getLastcoupondate().hashCode());
        result = prime * result + ((getNextcoupondate() == null) ? 0 : getNextcoupondate().hashCode());
        result = prime * result + ((getFundhouse() == null) ? 0 : getFundhouse().hashCode());
        result = prime * result + ((getTotalissuedshares() == null) ? 0 : getTotalissuedshares().hashCode());
        result = prime * result + ((getInstrumentsection() == null) ? 0 : getInstrumentsection().hashCode());
        result = prime * result + ((getCouponperiod() == null) ? 0 : getCouponperiod().hashCode());
        result = prime * result + ((getRateperiod() == null) ? 0 : getRateperiod().hashCode());
        result = prime * result + ((getConvertinstrument() == null) ? 0 : getConvertinstrument().hashCode());
        result = prime * result + ((getConvertmarket() == null) ? 0 : getConvertmarket().hashCode());
        result = prime * result + ((getConvertdepot() == null) ? 0 : getConvertdepot().hashCode());
        result = prime * result + ((getConvertlocation() == null) ? 0 : getConvertlocation().hashCode());
        result = prime * result + ((getConfirmdays() == null) ? 0 : getConfirmdays().hashCode());
        result = prime * result + ((getSettledays() == null) ? 0 : getSettledays().hashCode());
        result = prime * result + ((getElitype() == null) ? 0 : getElitype().hashCode());
        result = prime * result + ((getIssueprice() == null) ? 0 : getIssueprice().hashCode());
        result = prime * result + ((getStrikeprice() == null) ? 0 : getStrikeprice().hashCode());
        result = prime * result + ((getStrikepriceupper() == null) ? 0 : getStrikepriceupper().hashCode());
        result = prime * result + ((getSettlemode() == null) ? 0 : getSettlemode().hashCode());
        result = prime * result + ((getInstsettledate() == null) ? 0 : getInstsettledate().hashCode());
        result = prime * result + ((getIssuer() == null) ? 0 : getIssuer().hashCode());
        result = prime * result + ((getUnitrounding() == null) ? 0 : getUnitrounding().hashCode());
        result = prime * result + ((getRoundingtype() == null) ? 0 : getRoundingtype().hashCode());
        result = prime * result + ((getFundhousefee() == null) ? 0 : getFundhousefee().hashCode());
        result = prime * result + ((getAdditionalfee() == null) ? 0 : getAdditionalfee().hashCode());
        result = prime * result + ((getMinredemptedamount() == null) ? 0 : getMinredemptedamount().hashCode());
        result = prime * result + ((getMinremainingamount() == null) ? 0 : getMinremainingamount().hashCode());
        result = prime * result + ((getShorttradedays() == null) ? 0 : getShorttradedays().hashCode());
        result = prime * result + ((getSyncref() == null) ? 0 : getSyncref().hashCode());
        result = prime * result + ((getUnderindex() == null) ? 0 : getUnderindex().hashCode());
        result = prime * result + ((getCallprice() == null) ? 0 : getCallprice().hashCode());
        result = prime * result + ((getAastocks() == null) ? 0 : getAastocks().hashCode());
        result = prime * result + ((getPshk() == null) ? 0 : getPshk().hashCode());
        result = prime * result + ((getIsstaffexemption() == null) ? 0 : getIsstaffexemption().hashCode());
        result = prime * result + ((getVirtualasset() == null) ? 0 : getVirtualasset().hashCode());
        result = prime * result + ((getLogdatetime() == null) ? 0 : getLogdatetime().hashCode());
        result = prime * result + ((getLoghostname() == null) ? 0 : getLoghostname().hashCode());
        result = prime * result + ((getLogusername() == null) ? 0 : getLogusername().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InstrumentExtVersion
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", date=").append(date);
        sb.append(", instrument=").append(instrument);
        sb.append(", market=").append(market);
        sb.append(", defaultchargeccy=").append(defaultchargeccy);
        sb.append(", couponrate=").append(couponrate);
        sb.append(", priceinpercentoramount=").append(priceinpercentoramount);
        sb.append(", lastcoupondate=").append(lastcoupondate);
        sb.append(", nextcoupondate=").append(nextcoupondate);
        sb.append(", fundhouse=").append(fundhouse);
        sb.append(", totalissuedshares=").append(totalissuedshares);
        sb.append(", instrumentsection=").append(instrumentsection);
        sb.append(", couponperiod=").append(couponperiod);
        sb.append(", rateperiod=").append(rateperiod);
        sb.append(", convertinstrument=").append(convertinstrument);
        sb.append(", convertmarket=").append(convertmarket);
        sb.append(", convertdepot=").append(convertdepot);
        sb.append(", convertlocation=").append(convertlocation);
        sb.append(", confirmdays=").append(confirmdays);
        sb.append(", settledays=").append(settledays);
        sb.append(", elitype=").append(elitype);
        sb.append(", issueprice=").append(issueprice);
        sb.append(", strikeprice=").append(strikeprice);
        sb.append(", strikepriceupper=").append(strikepriceupper);
        sb.append(", settlemode=").append(settlemode);
        sb.append(", instsettledate=").append(instsettledate);
        sb.append(", issuer=").append(issuer);
        sb.append(", unitrounding=").append(unitrounding);
        sb.append(", roundingtype=").append(roundingtype);
        sb.append(", fundhousefee=").append(fundhousefee);
        sb.append(", additionalfee=").append(additionalfee);
        sb.append(", minredemptedamount=").append(minredemptedamount);
        sb.append(", minremainingamount=").append(minremainingamount);
        sb.append(", shorttradedays=").append(shorttradedays);
        sb.append(", syncref=").append(syncref);
        sb.append(", underindex=").append(underindex);
        sb.append(", callprice=").append(callprice);
        sb.append(", aastocks=").append(aastocks);
        sb.append(", pshk=").append(pshk);
        sb.append(", isstaffexemption=").append(isstaffexemption);
        sb.append(", virtualasset=").append(virtualasset);
        sb.append(", logdatetime=").append(logdatetime);
        sb.append(", loghostname=").append(loghostname);
        sb.append(", logusername=").append(logusername);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}