package com.example.migration.dao.master.entity;

import java.util.ArrayList;
import java.util.List;

public class TTLMarketBoardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public TTLMarketBoardExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMarketIsNull() {
            addCriterion("Market is null");
            return (Criteria) this;
        }

        public Criteria andMarketIsNotNull() {
            addCriterion("Market is not null");
            return (Criteria) this;
        }

        public Criteria andMarketEqualTo(String value) {
            addCriterion("Market =", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotEqualTo(String value) {
            addCriterion("Market <>", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThan(String value) {
            addCriterion("Market >", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThanOrEqualTo(String value) {
            addCriterion("Market >=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThan(String value) {
            addCriterion("Market <", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThanOrEqualTo(String value) {
            addCriterion("Market <=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLike(String value) {
            addCriterion("Market like", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotLike(String value) {
            addCriterion("Market not like", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketIn(List<String> values) {
            addCriterion("Market in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotIn(List<String> values) {
            addCriterion("Market not in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketBetween(String value1, String value2) {
            addCriterion("Market between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotBetween(String value1, String value2) {
            addCriterion("Market not between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidIsNull() {
            addCriterion("TTLMarketID is null");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidIsNotNull() {
            addCriterion("TTLMarketID is not null");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidEqualTo(String value) {
            addCriterion("TTLMarketID =", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidNotEqualTo(String value) {
            addCriterion("TTLMarketID <>", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidGreaterThan(String value) {
            addCriterion("TTLMarketID >", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidGreaterThanOrEqualTo(String value) {
            addCriterion("TTLMarketID >=", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidLessThan(String value) {
            addCriterion("TTLMarketID <", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidLessThanOrEqualTo(String value) {
            addCriterion("TTLMarketID <=", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidLike(String value) {
            addCriterion("TTLMarketID like", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidNotLike(String value) {
            addCriterion("TTLMarketID not like", value, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidIn(List<String> values) {
            addCriterion("TTLMarketID in", values, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidNotIn(List<String> values) {
            addCriterion("TTLMarketID not in", values, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidBetween(String value1, String value2) {
            addCriterion("TTLMarketID between", value1, value2, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidNotBetween(String value1, String value2) {
            addCriterion("TTLMarketID not between", value1, value2, "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidIsNull() {
            addCriterion("TTLBoardID is null");
            return (Criteria) this;
        }

        public Criteria andTtlboardidIsNotNull() {
            addCriterion("TTLBoardID is not null");
            return (Criteria) this;
        }

        public Criteria andTtlboardidEqualTo(String value) {
            addCriterion("TTLBoardID =", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidNotEqualTo(String value) {
            addCriterion("TTLBoardID <>", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidGreaterThan(String value) {
            addCriterion("TTLBoardID >", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidGreaterThanOrEqualTo(String value) {
            addCriterion("TTLBoardID >=", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidLessThan(String value) {
            addCriterion("TTLBoardID <", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidLessThanOrEqualTo(String value) {
            addCriterion("TTLBoardID <=", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidLike(String value) {
            addCriterion("TTLBoardID like", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidNotLike(String value) {
            addCriterion("TTLBoardID not like", value, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidIn(List<String> values) {
            addCriterion("TTLBoardID in", values, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidNotIn(List<String> values) {
            addCriterion("TTLBoardID not in", values, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidBetween(String value1, String value2) {
            addCriterion("TTLBoardID between", value1, value2, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidNotBetween(String value1, String value2) {
            addCriterion("TTLBoardID not between", value1, value2, "ttlboardid");
            return (Criteria) this;
        }

        public Criteria andMarketLikeInsensitive(String value) {
            addCriterion("upper(Market) like", value.toUpperCase(), "market");
            return (Criteria) this;
        }

        public Criteria andTtlmarketidLikeInsensitive(String value) {
            addCriterion("upper(TTLMarketID) like", value.toUpperCase(), "ttlmarketid");
            return (Criteria) this;
        }

        public Criteria andTtlboardidLikeInsensitive(String value) {
            addCriterion("upper(TTLBoardID) like", value.toUpperCase(), "ttlboardid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}