package com.example.migration.dao.master.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TTLMQOrders
 */
public class TTLMQOrders extends TTLMQOrdersKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.SeqNo
     *
     * @mbg.generated
     */
    private Integer seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.MQMessage
     *
     * @mbg.generated
     */
    private String mqmessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.ReferenceID
     *
     * @mbg.generated
     */
    private String referenceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.Action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.ChannelID
     *
     * @mbg.generated
     */
    private String channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.SubAccountID
     *
     * @mbg.generated
     */
    private String subaccountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.BS
     *
     * @mbg.generated
     */
    private String bs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.MarketID
     *
     * @mbg.generated
     */
    private String marketid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.BoardID
     *
     * @mbg.generated
     */
    private String boardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.InstrumentID
     *
     * @mbg.generated
     */
    private String instrumentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.Qty
     *
     * @mbg.generated
     */
    private BigDecimal qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.GrossAmt
     *
     * @mbg.generated
     */
    private BigDecimal grossamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.NetAmt
     *
     * @mbg.generated
     */
    private BigDecimal netamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.FilledQty
     *
     * @mbg.generated
     */
    private BigDecimal filledqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.Price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.TradeDate
     *
     * @mbg.generated
     */
    private String tradedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.SettleDate
     *
     * @mbg.generated
     */
    private String settledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.CurrencyID
     *
     * @mbg.generated
     */
    private String currencyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.Status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.OrderGroupID
     *
     * @mbg.generated
     */
    private String ordergroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.Remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.UserID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.TxnType
     *
     * @mbg.generated
     */
    private String txntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.CashLedgerDelta
     *
     * @mbg.generated
     */
    private String cashledgerdelta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.InstLedgerDelta
     *
     * @mbg.generated
     */
    private String instledgerdelta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.CashSettleDelta
     *
     * @mbg.generated
     */
    private String cashsettledelta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.InstSettleDelta
     *
     * @mbg.generated
     */
    private String instsettledelta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.MQDate
     *
     * @mbg.generated
     */
    private Date mqdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.MQStatus
     *
     * @mbg.generated
     */
    private String mqstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.SQLMessage
     *
     * @mbg.generated
     */
    private String sqlmessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.ExecutionQty
     *
     * @mbg.generated
     */
    private BigDecimal executionqty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.ExecutionPrice
     *
     * @mbg.generated
     */
    private BigDecimal executionprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.InputDatetime
     *
     * @mbg.generated
     */
    private Date inputdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.AmendDatetime
     *
     * @mbg.generated
     */
    private Date amenddatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.FinalExecDatetime
     *
     * @mbg.generated
     */
    private Date finalexecdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.SeqNo
     *
     * @return the value of TTLMQOrders.SeqNo
     *
     * @mbg.generated
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.SeqNo
     *
     * @param seqno the value for TTLMQOrders.SeqNo
     *
     * @mbg.generated
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.MQMessage
     *
     * @return the value of TTLMQOrders.MQMessage
     *
     * @mbg.generated
     */
    public String getMqmessage() {
        return mqmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.MQMessage
     *
     * @param mqmessage the value for TTLMQOrders.MQMessage
     *
     * @mbg.generated
     */
    public void setMqmessage(String mqmessage) {
        this.mqmessage = mqmessage == null ? null : mqmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.ReferenceID
     *
     * @return the value of TTLMQOrders.ReferenceID
     *
     * @mbg.generated
     */
    public String getReferenceid() {
        return referenceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.ReferenceID
     *
     * @param referenceid the value for TTLMQOrders.ReferenceID
     *
     * @mbg.generated
     */
    public void setReferenceid(String referenceid) {
        this.referenceid = referenceid == null ? null : referenceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.Action
     *
     * @return the value of TTLMQOrders.Action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.Action
     *
     * @param action the value for TTLMQOrders.Action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.ChannelID
     *
     * @return the value of TTLMQOrders.ChannelID
     *
     * @mbg.generated
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.ChannelID
     *
     * @param channelid the value for TTLMQOrders.ChannelID
     *
     * @mbg.generated
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.SubAccountID
     *
     * @return the value of TTLMQOrders.SubAccountID
     *
     * @mbg.generated
     */
    public String getSubaccountid() {
        return subaccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.SubAccountID
     *
     * @param subaccountid the value for TTLMQOrders.SubAccountID
     *
     * @mbg.generated
     */
    public void setSubaccountid(String subaccountid) {
        this.subaccountid = subaccountid == null ? null : subaccountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.BS
     *
     * @return the value of TTLMQOrders.BS
     *
     * @mbg.generated
     */
    public String getBs() {
        return bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.BS
     *
     * @param bs the value for TTLMQOrders.BS
     *
     * @mbg.generated
     */
    public void setBs(String bs) {
        this.bs = bs == null ? null : bs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.MarketID
     *
     * @return the value of TTLMQOrders.MarketID
     *
     * @mbg.generated
     */
    public String getMarketid() {
        return marketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.MarketID
     *
     * @param marketid the value for TTLMQOrders.MarketID
     *
     * @mbg.generated
     */
    public void setMarketid(String marketid) {
        this.marketid = marketid == null ? null : marketid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.BoardID
     *
     * @return the value of TTLMQOrders.BoardID
     *
     * @mbg.generated
     */
    public String getBoardid() {
        return boardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.BoardID
     *
     * @param boardid the value for TTLMQOrders.BoardID
     *
     * @mbg.generated
     */
    public void setBoardid(String boardid) {
        this.boardid = boardid == null ? null : boardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.InstrumentID
     *
     * @return the value of TTLMQOrders.InstrumentID
     *
     * @mbg.generated
     */
    public String getInstrumentid() {
        return instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.InstrumentID
     *
     * @param instrumentid the value for TTLMQOrders.InstrumentID
     *
     * @mbg.generated
     */
    public void setInstrumentid(String instrumentid) {
        this.instrumentid = instrumentid == null ? null : instrumentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.Qty
     *
     * @return the value of TTLMQOrders.Qty
     *
     * @mbg.generated
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.Qty
     *
     * @param qty the value for TTLMQOrders.Qty
     *
     * @mbg.generated
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.GrossAmt
     *
     * @return the value of TTLMQOrders.GrossAmt
     *
     * @mbg.generated
     */
    public BigDecimal getGrossamt() {
        return grossamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.GrossAmt
     *
     * @param grossamt the value for TTLMQOrders.GrossAmt
     *
     * @mbg.generated
     */
    public void setGrossamt(BigDecimal grossamt) {
        this.grossamt = grossamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.NetAmt
     *
     * @return the value of TTLMQOrders.NetAmt
     *
     * @mbg.generated
     */
    public BigDecimal getNetamt() {
        return netamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.NetAmt
     *
     * @param netamt the value for TTLMQOrders.NetAmt
     *
     * @mbg.generated
     */
    public void setNetamt(BigDecimal netamt) {
        this.netamt = netamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.FilledQty
     *
     * @return the value of TTLMQOrders.FilledQty
     *
     * @mbg.generated
     */
    public BigDecimal getFilledqty() {
        return filledqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.FilledQty
     *
     * @param filledqty the value for TTLMQOrders.FilledQty
     *
     * @mbg.generated
     */
    public void setFilledqty(BigDecimal filledqty) {
        this.filledqty = filledqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.Price
     *
     * @return the value of TTLMQOrders.Price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.Price
     *
     * @param price the value for TTLMQOrders.Price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.TradeDate
     *
     * @return the value of TTLMQOrders.TradeDate
     *
     * @mbg.generated
     */
    public String getTradedate() {
        return tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.TradeDate
     *
     * @param tradedate the value for TTLMQOrders.TradeDate
     *
     * @mbg.generated
     */
    public void setTradedate(String tradedate) {
        this.tradedate = tradedate == null ? null : tradedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.SettleDate
     *
     * @return the value of TTLMQOrders.SettleDate
     *
     * @mbg.generated
     */
    public String getSettledate() {
        return settledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.SettleDate
     *
     * @param settledate the value for TTLMQOrders.SettleDate
     *
     * @mbg.generated
     */
    public void setSettledate(String settledate) {
        this.settledate = settledate == null ? null : settledate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.CurrencyID
     *
     * @return the value of TTLMQOrders.CurrencyID
     *
     * @mbg.generated
     */
    public String getCurrencyid() {
        return currencyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.CurrencyID
     *
     * @param currencyid the value for TTLMQOrders.CurrencyID
     *
     * @mbg.generated
     */
    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid == null ? null : currencyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.Status
     *
     * @return the value of TTLMQOrders.Status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.Status
     *
     * @param status the value for TTLMQOrders.Status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.OrderGroupID
     *
     * @return the value of TTLMQOrders.OrderGroupID
     *
     * @mbg.generated
     */
    public String getOrdergroupid() {
        return ordergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.OrderGroupID
     *
     * @param ordergroupid the value for TTLMQOrders.OrderGroupID
     *
     * @mbg.generated
     */
    public void setOrdergroupid(String ordergroupid) {
        this.ordergroupid = ordergroupid == null ? null : ordergroupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.Remarks
     *
     * @return the value of TTLMQOrders.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.Remarks
     *
     * @param remarks the value for TTLMQOrders.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.UserID
     *
     * @return the value of TTLMQOrders.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.UserID
     *
     * @param userid the value for TTLMQOrders.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.TxnType
     *
     * @return the value of TTLMQOrders.TxnType
     *
     * @mbg.generated
     */
    public String getTxntype() {
        return txntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.TxnType
     *
     * @param txntype the value for TTLMQOrders.TxnType
     *
     * @mbg.generated
     */
    public void setTxntype(String txntype) {
        this.txntype = txntype == null ? null : txntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.CashLedgerDelta
     *
     * @return the value of TTLMQOrders.CashLedgerDelta
     *
     * @mbg.generated
     */
    public String getCashledgerdelta() {
        return cashledgerdelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.CashLedgerDelta
     *
     * @param cashledgerdelta the value for TTLMQOrders.CashLedgerDelta
     *
     * @mbg.generated
     */
    public void setCashledgerdelta(String cashledgerdelta) {
        this.cashledgerdelta = cashledgerdelta == null ? null : cashledgerdelta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.InstLedgerDelta
     *
     * @return the value of TTLMQOrders.InstLedgerDelta
     *
     * @mbg.generated
     */
    public String getInstledgerdelta() {
        return instledgerdelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.InstLedgerDelta
     *
     * @param instledgerdelta the value for TTLMQOrders.InstLedgerDelta
     *
     * @mbg.generated
     */
    public void setInstledgerdelta(String instledgerdelta) {
        this.instledgerdelta = instledgerdelta == null ? null : instledgerdelta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.CashSettleDelta
     *
     * @return the value of TTLMQOrders.CashSettleDelta
     *
     * @mbg.generated
     */
    public String getCashsettledelta() {
        return cashsettledelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.CashSettleDelta
     *
     * @param cashsettledelta the value for TTLMQOrders.CashSettleDelta
     *
     * @mbg.generated
     */
    public void setCashsettledelta(String cashsettledelta) {
        this.cashsettledelta = cashsettledelta == null ? null : cashsettledelta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.InstSettleDelta
     *
     * @return the value of TTLMQOrders.InstSettleDelta
     *
     * @mbg.generated
     */
    public String getInstsettledelta() {
        return instsettledelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.InstSettleDelta
     *
     * @param instsettledelta the value for TTLMQOrders.InstSettleDelta
     *
     * @mbg.generated
     */
    public void setInstsettledelta(String instsettledelta) {
        this.instsettledelta = instsettledelta == null ? null : instsettledelta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.MQDate
     *
     * @return the value of TTLMQOrders.MQDate
     *
     * @mbg.generated
     */
    public Date getMqdate() {
        return mqdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.MQDate
     *
     * @param mqdate the value for TTLMQOrders.MQDate
     *
     * @mbg.generated
     */
    public void setMqdate(Date mqdate) {
        this.mqdate = mqdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.MQStatus
     *
     * @return the value of TTLMQOrders.MQStatus
     *
     * @mbg.generated
     */
    public String getMqstatus() {
        return mqstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.MQStatus
     *
     * @param mqstatus the value for TTLMQOrders.MQStatus
     *
     * @mbg.generated
     */
    public void setMqstatus(String mqstatus) {
        this.mqstatus = mqstatus == null ? null : mqstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.SQLMessage
     *
     * @return the value of TTLMQOrders.SQLMessage
     *
     * @mbg.generated
     */
    public String getSqlmessage() {
        return sqlmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.SQLMessage
     *
     * @param sqlmessage the value for TTLMQOrders.SQLMessage
     *
     * @mbg.generated
     */
    public void setSqlmessage(String sqlmessage) {
        this.sqlmessage = sqlmessage == null ? null : sqlmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.ExecutionQty
     *
     * @return the value of TTLMQOrders.ExecutionQty
     *
     * @mbg.generated
     */
    public BigDecimal getExecutionqty() {
        return executionqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.ExecutionQty
     *
     * @param executionqty the value for TTLMQOrders.ExecutionQty
     *
     * @mbg.generated
     */
    public void setExecutionqty(BigDecimal executionqty) {
        this.executionqty = executionqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.ExecutionPrice
     *
     * @return the value of TTLMQOrders.ExecutionPrice
     *
     * @mbg.generated
     */
    public BigDecimal getExecutionprice() {
        return executionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.ExecutionPrice
     *
     * @param executionprice the value for TTLMQOrders.ExecutionPrice
     *
     * @mbg.generated
     */
    public void setExecutionprice(BigDecimal executionprice) {
        this.executionprice = executionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.InputDatetime
     *
     * @return the value of TTLMQOrders.InputDatetime
     *
     * @mbg.generated
     */
    public Date getInputdatetime() {
        return inputdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.InputDatetime
     *
     * @param inputdatetime the value for TTLMQOrders.InputDatetime
     *
     * @mbg.generated
     */
    public void setInputdatetime(Date inputdatetime) {
        this.inputdatetime = inputdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.AmendDatetime
     *
     * @return the value of TTLMQOrders.AmendDatetime
     *
     * @mbg.generated
     */
    public Date getAmenddatetime() {
        return amenddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.AmendDatetime
     *
     * @param amenddatetime the value for TTLMQOrders.AmendDatetime
     *
     * @mbg.generated
     */
    public void setAmenddatetime(Date amenddatetime) {
        this.amenddatetime = amenddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.FinalExecDatetime
     *
     * @return the value of TTLMQOrders.FinalExecDatetime
     *
     * @mbg.generated
     */
    public Date getFinalexecdatetime() {
        return finalexecdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.FinalExecDatetime
     *
     * @param finalexecdatetime the value for TTLMQOrders.FinalExecDatetime
     *
     * @mbg.generated
     */
    public void setFinalexecdatetime(Date finalexecdatetime) {
        this.finalexecdatetime = finalexecdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TTLMQOrders other = (TTLMQOrders) that;
        return (this.getMqdatetime() == null ? other.getMqdatetime() == null : this.getMqdatetime().equals(other.getMqdatetime()))
            && (this.getHostname() == null ? other.getHostname() == null : this.getHostname().equals(other.getHostname()))
            && (this.getOrderrefid() == null ? other.getOrderrefid() == null : this.getOrderrefid().equals(other.getOrderrefid()))
            && (this.getSeqno() == null ? other.getSeqno() == null : this.getSeqno().equals(other.getSeqno()))
            && (this.getMqmessage() == null ? other.getMqmessage() == null : this.getMqmessage().equals(other.getMqmessage()))
            && (this.getReferenceid() == null ? other.getReferenceid() == null : this.getReferenceid().equals(other.getReferenceid()))
            && (this.getAction() == null ? other.getAction() == null : this.getAction().equals(other.getAction()))
            && (this.getChannelid() == null ? other.getChannelid() == null : this.getChannelid().equals(other.getChannelid()))
            && (this.getSubaccountid() == null ? other.getSubaccountid() == null : this.getSubaccountid().equals(other.getSubaccountid()))
            && (this.getBs() == null ? other.getBs() == null : this.getBs().equals(other.getBs()))
            && (this.getMarketid() == null ? other.getMarketid() == null : this.getMarketid().equals(other.getMarketid()))
            && (this.getBoardid() == null ? other.getBoardid() == null : this.getBoardid().equals(other.getBoardid()))
            && (this.getInstrumentid() == null ? other.getInstrumentid() == null : this.getInstrumentid().equals(other.getInstrumentid()))
            && (this.getQty() == null ? other.getQty() == null : this.getQty().equals(other.getQty()))
            && (this.getGrossamt() == null ? other.getGrossamt() == null : this.getGrossamt().equals(other.getGrossamt()))
            && (this.getNetamt() == null ? other.getNetamt() == null : this.getNetamt().equals(other.getNetamt()))
            && (this.getFilledqty() == null ? other.getFilledqty() == null : this.getFilledqty().equals(other.getFilledqty()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getTradedate() == null ? other.getTradedate() == null : this.getTradedate().equals(other.getTradedate()))
            && (this.getSettledate() == null ? other.getSettledate() == null : this.getSettledate().equals(other.getSettledate()))
            && (this.getCurrencyid() == null ? other.getCurrencyid() == null : this.getCurrencyid().equals(other.getCurrencyid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOrdergroupid() == null ? other.getOrdergroupid() == null : this.getOrdergroupid().equals(other.getOrdergroupid()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getTxntype() == null ? other.getTxntype() == null : this.getTxntype().equals(other.getTxntype()))
            && (this.getCashledgerdelta() == null ? other.getCashledgerdelta() == null : this.getCashledgerdelta().equals(other.getCashledgerdelta()))
            && (this.getInstledgerdelta() == null ? other.getInstledgerdelta() == null : this.getInstledgerdelta().equals(other.getInstledgerdelta()))
            && (this.getCashsettledelta() == null ? other.getCashsettledelta() == null : this.getCashsettledelta().equals(other.getCashsettledelta()))
            && (this.getInstsettledelta() == null ? other.getInstsettledelta() == null : this.getInstsettledelta().equals(other.getInstsettledelta()))
            && (this.getMqdate() == null ? other.getMqdate() == null : this.getMqdate().equals(other.getMqdate()))
            && (this.getMqstatus() == null ? other.getMqstatus() == null : this.getMqstatus().equals(other.getMqstatus()))
            && (this.getSqlmessage() == null ? other.getSqlmessage() == null : this.getSqlmessage().equals(other.getSqlmessage()))
            && (this.getExecutionqty() == null ? other.getExecutionqty() == null : this.getExecutionqty().equals(other.getExecutionqty()))
            && (this.getExecutionprice() == null ? other.getExecutionprice() == null : this.getExecutionprice().equals(other.getExecutionprice()))
            && (this.getInputdatetime() == null ? other.getInputdatetime() == null : this.getInputdatetime().equals(other.getInputdatetime()))
            && (this.getAmenddatetime() == null ? other.getAmenddatetime() == null : this.getAmenddatetime().equals(other.getAmenddatetime()))
            && (this.getFinalexecdatetime() == null ? other.getFinalexecdatetime() == null : this.getFinalexecdatetime().equals(other.getFinalexecdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMqdatetime() == null) ? 0 : getMqdatetime().hashCode());
        result = prime * result + ((getHostname() == null) ? 0 : getHostname().hashCode());
        result = prime * result + ((getOrderrefid() == null) ? 0 : getOrderrefid().hashCode());
        result = prime * result + ((getSeqno() == null) ? 0 : getSeqno().hashCode());
        result = prime * result + ((getMqmessage() == null) ? 0 : getMqmessage().hashCode());
        result = prime * result + ((getReferenceid() == null) ? 0 : getReferenceid().hashCode());
        result = prime * result + ((getAction() == null) ? 0 : getAction().hashCode());
        result = prime * result + ((getChannelid() == null) ? 0 : getChannelid().hashCode());
        result = prime * result + ((getSubaccountid() == null) ? 0 : getSubaccountid().hashCode());
        result = prime * result + ((getBs() == null) ? 0 : getBs().hashCode());
        result = prime * result + ((getMarketid() == null) ? 0 : getMarketid().hashCode());
        result = prime * result + ((getBoardid() == null) ? 0 : getBoardid().hashCode());
        result = prime * result + ((getInstrumentid() == null) ? 0 : getInstrumentid().hashCode());
        result = prime * result + ((getQty() == null) ? 0 : getQty().hashCode());
        result = prime * result + ((getGrossamt() == null) ? 0 : getGrossamt().hashCode());
        result = prime * result + ((getNetamt() == null) ? 0 : getNetamt().hashCode());
        result = prime * result + ((getFilledqty() == null) ? 0 : getFilledqty().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getTradedate() == null) ? 0 : getTradedate().hashCode());
        result = prime * result + ((getSettledate() == null) ? 0 : getSettledate().hashCode());
        result = prime * result + ((getCurrencyid() == null) ? 0 : getCurrencyid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOrdergroupid() == null) ? 0 : getOrdergroupid().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getTxntype() == null) ? 0 : getTxntype().hashCode());
        result = prime * result + ((getCashledgerdelta() == null) ? 0 : getCashledgerdelta().hashCode());
        result = prime * result + ((getInstledgerdelta() == null) ? 0 : getInstledgerdelta().hashCode());
        result = prime * result + ((getCashsettledelta() == null) ? 0 : getCashsettledelta().hashCode());
        result = prime * result + ((getInstsettledelta() == null) ? 0 : getInstsettledelta().hashCode());
        result = prime * result + ((getMqdate() == null) ? 0 : getMqdate().hashCode());
        result = prime * result + ((getMqstatus() == null) ? 0 : getMqstatus().hashCode());
        result = prime * result + ((getSqlmessage() == null) ? 0 : getSqlmessage().hashCode());
        result = prime * result + ((getExecutionqty() == null) ? 0 : getExecutionqty().hashCode());
        result = prime * result + ((getExecutionprice() == null) ? 0 : getExecutionprice().hashCode());
        result = prime * result + ((getInputdatetime() == null) ? 0 : getInputdatetime().hashCode());
        result = prime * result + ((getAmenddatetime() == null) ? 0 : getAmenddatetime().hashCode());
        result = prime * result + ((getFinalexecdatetime() == null) ? 0 : getFinalexecdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqno=").append(seqno);
        sb.append(", mqmessage=").append(mqmessage);
        sb.append(", referenceid=").append(referenceid);
        sb.append(", action=").append(action);
        sb.append(", channelid=").append(channelid);
        sb.append(", subaccountid=").append(subaccountid);
        sb.append(", bs=").append(bs);
        sb.append(", marketid=").append(marketid);
        sb.append(", boardid=").append(boardid);
        sb.append(", instrumentid=").append(instrumentid);
        sb.append(", qty=").append(qty);
        sb.append(", grossamt=").append(grossamt);
        sb.append(", netamt=").append(netamt);
        sb.append(", filledqty=").append(filledqty);
        sb.append(", price=").append(price);
        sb.append(", tradedate=").append(tradedate);
        sb.append(", settledate=").append(settledate);
        sb.append(", currencyid=").append(currencyid);
        sb.append(", status=").append(status);
        sb.append(", ordergroupid=").append(ordergroupid);
        sb.append(", remarks=").append(remarks);
        sb.append(", userid=").append(userid);
        sb.append(", txntype=").append(txntype);
        sb.append(", cashledgerdelta=").append(cashledgerdelta);
        sb.append(", instledgerdelta=").append(instledgerdelta);
        sb.append(", cashsettledelta=").append(cashsettledelta);
        sb.append(", instsettledelta=").append(instsettledelta);
        sb.append(", mqdate=").append(mqdate);
        sb.append(", mqstatus=").append(mqstatus);
        sb.append(", sqlmessage=").append(sqlmessage);
        sb.append(", executionqty=").append(executionqty);
        sb.append(", executionprice=").append(executionprice);
        sb.append(", inputdatetime=").append(inputdatetime);
        sb.append(", amenddatetime=").append(amenddatetime);
        sb.append(", finalexecdatetime=").append(finalexecdatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}