package com.example.migration.dao.master.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TTLMarketBoard
 */
public class TTLMarketBoard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMarketBoard.Market
     *
     * @mbg.generated
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMarketBoard.TTLMarketID
     *
     * @mbg.generated
     */
    private String ttlmarketid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMarketBoard.TTLBoardID
     *
     * @mbg.generated
     */
    private String ttlboardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMarketBoard.Market
     *
     * @return the value of TTLMarketBoard.Market
     *
     * @mbg.generated
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMarketBoard.Market
     *
     * @param market the value for TTLMarketBoard.Market
     *
     * @mbg.generated
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMarketBoard.TTLMarketID
     *
     * @return the value of TTLMarketBoard.TTLMarketID
     *
     * @mbg.generated
     */
    public String getTtlmarketid() {
        return ttlmarketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMarketBoard.TTLMarketID
     *
     * @param ttlmarketid the value for TTLMarketBoard.TTLMarketID
     *
     * @mbg.generated
     */
    public void setTtlmarketid(String ttlmarketid) {
        this.ttlmarketid = ttlmarketid == null ? null : ttlmarketid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMarketBoard.TTLBoardID
     *
     * @return the value of TTLMarketBoard.TTLBoardID
     *
     * @mbg.generated
     */
    public String getTtlboardid() {
        return ttlboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMarketBoard.TTLBoardID
     *
     * @param ttlboardid the value for TTLMarketBoard.TTLBoardID
     *
     * @mbg.generated
     */
    public void setTtlboardid(String ttlboardid) {
        this.ttlboardid = ttlboardid == null ? null : ttlboardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TTLMarketBoard other = (TTLMarketBoard) that;
        return (this.getMarket() == null ? other.getMarket() == null : this.getMarket().equals(other.getMarket()))
            && (this.getTtlmarketid() == null ? other.getTtlmarketid() == null : this.getTtlmarketid().equals(other.getTtlmarketid()))
            && (this.getTtlboardid() == null ? other.getTtlboardid() == null : this.getTtlboardid().equals(other.getTtlboardid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMarket() == null) ? 0 : getMarket().hashCode());
        result = prime * result + ((getTtlmarketid() == null) ? 0 : getTtlmarketid().hashCode());
        result = prime * result + ((getTtlboardid() == null) ? 0 : getTtlboardid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMarketBoard
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", market=").append(market);
        sb.append(", ttlmarketid=").append(ttlmarketid);
        sb.append(", ttlboardid=").append(ttlboardid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}