package com.example.migration.dao.master.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TTLMQOrders
 */
public class TTLMQOrdersKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.MQDateTime
     *
     * @mbg.generated
     */
    private Date mqdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.HostName
     *
     * @mbg.generated
     */
    private String hostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TTLMQOrders.OrderRefID
     *
     * @mbg.generated
     */
    private String orderrefid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.MQDateTime
     *
     * @return the value of TTLMQOrders.MQDateTime
     *
     * @mbg.generated
     */
    public Date getMqdatetime() {
        return mqdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.MQDateTime
     *
     * @param mqdatetime the value for TTLMQOrders.MQDateTime
     *
     * @mbg.generated
     */
    public void setMqdatetime(Date mqdatetime) {
        this.mqdatetime = mqdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.HostName
     *
     * @return the value of TTLMQOrders.HostName
     *
     * @mbg.generated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.HostName
     *
     * @param hostname the value for TTLMQOrders.HostName
     *
     * @mbg.generated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TTLMQOrders.OrderRefID
     *
     * @return the value of TTLMQOrders.OrderRefID
     *
     * @mbg.generated
     */
    public String getOrderrefid() {
        return orderrefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TTLMQOrders.OrderRefID
     *
     * @param orderrefid the value for TTLMQOrders.OrderRefID
     *
     * @mbg.generated
     */
    public void setOrderrefid(String orderrefid) {
        this.orderrefid = orderrefid == null ? null : orderrefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TTLMQOrdersKey other = (TTLMQOrdersKey) that;
        return (this.getMqdatetime() == null ? other.getMqdatetime() == null : this.getMqdatetime().equals(other.getMqdatetime()))
            && (this.getHostname() == null ? other.getHostname() == null : this.getHostname().equals(other.getHostname()))
            && (this.getOrderrefid() == null ? other.getOrderrefid() == null : this.getOrderrefid().equals(other.getOrderrefid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMqdatetime() == null) ? 0 : getMqdatetime().hashCode());
        result = prime * result + ((getHostname() == null) ? 0 : getHostname().hashCode());
        result = prime * result + ((getOrderrefid() == null) ? 0 : getOrderrefid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TTLMQOrders
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mqdatetime=").append(mqdatetime);
        sb.append(", hostname=").append(hostname);
        sb.append(", orderrefid=").append(orderrefid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}