package com.example.migration.dao.slave.mapper;

import com.example.migration.dao.slave.entity.Vcbaccount;
import com.example.migration.dao.slave.entity.VcbaccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VcbaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    long countByExample(VcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int deleteByExample(VcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int insert(Vcbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int insertSelective(Vcbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    List<Vcbaccount> selectByExampleWithRowbounds(VcbaccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    List<Vcbaccount> selectByExample(VcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vcbaccount record, @Param("example") VcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vcbaccount record, @Param("example") VcbaccountExample example);
}