package com.example.migration.dao.slave.mapper;

import com.example.migration.dao.slave.entity.vcbaccount;
import com.example.migration.dao.slave.entity.vcbaccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface vcbaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    long countByExample(vcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int deleteByExample(vcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int insert(vcbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int insertSelective(vcbaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    List<vcbaccount> selectByExampleWithRowbounds(vcbaccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    List<vcbaccount> selectByExample(vcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") vcbaccount record, @Param("example") vcbaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBACCOUNT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") vcbaccount record, @Param("example") vcbaccountExample example);
}