package com.example.migration.dao.slave.mapper;

import com.example.migration.dao.slave.entity.Vcbtradingacc;
import com.example.migration.dao.slave.entity.VcbtradingaccExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VcbtradingaccMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    long countByExample(VcbtradingaccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    int deleteByExample(VcbtradingaccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    int insert(Vcbtradingacc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    int insertSelective(Vcbtradingacc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    List<Vcbtradingacc> selectByExampleWithRowbounds(VcbtradingaccExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    List<Vcbtradingacc> selectByExample(VcbtradingaccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vcbtradingacc record, @Param("example") VcbtradingaccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VCBTRADINGACC
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vcbtradingacc record, @Param("example") VcbtradingaccExample example);

    List<Vcbtradingacc> selectByExampleWithLimit();
}